2023-07-11 11:07:35,584 INFO    StreamThr :102694 [internal.py:wandb_internal():86] W&B internal server running at pid: 102694, started at: 2023-07-11 11:07:35.583804
2023-07-11 11:07:35,587 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status
2023-07-11 11:07:35,589 INFO    WriterThread:102694 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_110735-vv9iv6jn/run-vv9iv6jn.wandb
2023-07-11 11:07:35,591 DEBUG   SenderThread:102694 [sender.py:send():369] send: header
2023-07-11 11:07:35,592 DEBUG   SenderThread:102694 [sender.py:send():369] send: run
2023-07-11 11:07:36,457 INFO    SenderThread:102694 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_110735-vv9iv6jn/files
2023-07-11 11:07:36,457 INFO    SenderThread:102694 [sender.py:_start_run_threads():1100] run started: vv9iv6jn with start time 1689044855.58348
2023-07-11 11:07:36,457 DEBUG   SenderThread:102694 [sender.py:send_request():396] send_request: summary_record
2023-07-11 11:07:36,458 INFO    SenderThread:102694 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-11 11:07:36,466 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: check_version
2023-07-11 11:07:36,466 DEBUG   SenderThread:102694 [sender.py:send_request():396] send_request: check_version
2023-07-11 11:07:36,661 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: run_start
2023-07-11 11:07:36,666 DEBUG   HandlerThread:102694 [system_info.py:__init__():31] System info init
2023-07-11 11:07:36,666 DEBUG   HandlerThread:102694 [system_info.py:__init__():46] System info init done
2023-07-11 11:07:36,666 INFO    HandlerThread:102694 [system_monitor.py:start():181] Starting system monitor
2023-07-11 11:07:36,667 INFO    HandlerThread:102694 [system_monitor.py:probe():201] Collecting system info
2023-07-11 11:07:36,667 INFO    SystemMonitor:102694 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-11 11:07:36,669 INFO    SystemMonitor:102694 [interfaces.py:start():190] Started cpu monitoring
2023-07-11 11:07:36,670 INFO    SystemMonitor:102694 [interfaces.py:start():190] Started disk monitoring
2023-07-11 11:07:36,671 INFO    SystemMonitor:102694 [interfaces.py:start():190] Started gpu monitoring
2023-07-11 11:07:36,672 INFO    SystemMonitor:102694 [interfaces.py:start():190] Started memory monitoring
2023-07-11 11:07:36,673 INFO    SystemMonitor:102694 [interfaces.py:start():190] Started network monitoring
2023-07-11 11:07:36,685 DEBUG   HandlerThread:102694 [system_info.py:probe():195] Probing system
2023-07-11 11:07:36,688 DEBUG   HandlerThread:102694 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-11 11:07:36,688 DEBUG   HandlerThread:102694 [system_info.py:probe():240] Probing system done
2023-07-11 11:07:36,688 DEBUG   HandlerThread:102694 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-11T03:07:36.685264', 'startedAt': '2023-07-11T03:07:35.573300', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 4049.4195416666666, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 4628.201, 'min': 800.0, 'max': 5100.0}, {'current': 4629.145, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5085.47, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 4099.962, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 4099.455, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 4071.134, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.019298553466796875}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-11 11:07:36,689 INFO    HandlerThread:102694 [system_monitor.py:probe():211] Finished collecting system info
2023-07-11 11:07:36,689 INFO    HandlerThread:102694 [system_monitor.py:probe():214] Publishing system info
2023-07-11 11:07:36,689 DEBUG   HandlerThread:102694 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-11 11:07:36,689 DEBUG   HandlerThread:102694 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-11 11:07:36,689 DEBUG   HandlerThread:102694 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-11 11:07:37,461 INFO    Thread-17 :102694 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_110735-vv9iv6jn/files/requirements.txt
2023-07-11 11:07:37,462 INFO    Thread-17 :102694 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_110735-vv9iv6jn/files/conda-environment.yaml
2023-07-11 11:07:37,462 INFO    Thread-17 :102694 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_110735-vv9iv6jn/files/wandb-summary.json
2023-07-11 11:07:37,667 DEBUG   HandlerThread:102694 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-11 11:07:37,668 INFO    HandlerThread:102694 [system_monitor.py:probe():216] Finished publishing system info
2023-07-11 11:07:37,671 DEBUG   SenderThread:102694 [sender.py:send():369] send: files
2023-07-11 11:07:37,671 INFO    SenderThread:102694 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-11 11:07:37,677 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 11:07:37,678 DEBUG   SenderThread:102694 [sender.py:send_request():396] send_request: stop_status
2023-07-11 11:07:38,165 ERROR   wandb-upload_0:102694 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/vv9iv6jn/wandb-metadata.json?Expires=1689131257&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HM%2FZPhmTFyrAfR2qDrANLgyhpJcRLazP%2BslcVtxpWe7AaHd5OLdE%2BEemf5eIRoggCbg222mUzK%2Fx0E%2BVt3k67kiBOASpQFjq63FErchpj61DrFdXsT7eKMcGaqs%2BofB0vXLnwwdAjJ3n4vQm%2FSeT3onZpfU1F4lkq8CAXje8db0Gbn6lcVV4y1ULRfryswkqhVR500Mxjb4%2B4EXKmzU51nTkE1uqkMrKLibZjBGHa91sEbMUoqfKbzveKF0k2ksX24Uff44wQweoj7%2FQtY1PyRbtvixZ6%2BYJ3gqx5qtadyFQJPSX0oDfvNFa%2BQVipfvR7ua5uahf3gdA9bngCMGcWA%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/vv9iv6jn/wandb-metadata.json?Expires=1689131257&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HM%2FZPhmTFyrAfR2qDrANLgyhpJcRLazP%2BslcVtxpWe7AaHd5OLdE%2BEemf5eIRoggCbg222mUzK%2Fx0E%2BVt3k67kiBOASpQFjq63FErchpj61DrFdXsT7eKMcGaqs%2BofB0vXLnwwdAjJ3n4vQm%2FSeT3onZpfU1F4lkq8CAXje8db0Gbn6lcVV4y1ULRfryswkqhVR500Mxjb4%2B4EXKmzU51nTkE1uqkMrKLibZjBGHa91sEbMUoqfKbzveKF0k2ksX24Uff44wQweoj7%2FQtY1PyRbtvixZ6%2BYJ3gqx5qtadyFQJPSX0oDfvNFa%2BQVipfvR7ua5uahf3gdA9bngCMGcWA%3D%3D
2023-07-11 11:07:38,165 ERROR   wandb-upload_0:102694 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3617'}
2023-07-11 11:07:38,165 ERROR   wandb-upload_0:102694 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/vv9iv6jn/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-11 11:07:38,284 DEBUG   SenderThread:102694 [sender.py:send():369] send: telemetry
2023-07-11 11:07:38,460 INFO    Thread-17 :102694 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_110735-vv9iv6jn/files/conda-environment.yaml
2023-07-11 11:07:38,461 INFO    Thread-17 :102694 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_110735-vv9iv6jn/files/output.log
2023-07-11 11:07:38,461 INFO    Thread-17 :102694 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_110735-vv9iv6jn/files/wandb-metadata.json
2023-07-11 11:07:39,627 ERROR   wandb-upload_0:102694 [upload_job.py:push():136] Failed to upload file: /tmp/tmpt35wymvcwandb/yyheb7s2-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/vv9iv6jn/wandb-metadata.json?Expires=1689131257&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HM%2FZPhmTFyrAfR2qDrANLgyhpJcRLazP%2BslcVtxpWe7AaHd5OLdE%2BEemf5eIRoggCbg222mUzK%2Fx0E%2BVt3k67kiBOASpQFjq63FErchpj61DrFdXsT7eKMcGaqs%2BofB0vXLnwwdAjJ3n4vQm%2FSeT3onZpfU1F4lkq8CAXje8db0Gbn6lcVV4y1ULRfryswkqhVR500Mxjb4%2B4EXKmzU51nTkE1uqkMrKLibZjBGHa91sEbMUoqfKbzveKF0k2ksX24Uff44wQweoj7%2FQtY1PyRbtvixZ6%2BYJ3gqx5qtadyFQJPSX0oDfvNFa%2BQVipfvR7ua5uahf3gdA9bngCMGcWA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 11:07:39,844 ERROR   Thread-16 :102694 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpt35wymvcwandb/yyheb7s2-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/vv9iv6jn/wandb-metadata.json?Expires=1689131257&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=HM%2FZPhmTFyrAfR2qDrANLgyhpJcRLazP%2BslcVtxpWe7AaHd5OLdE%2BEemf5eIRoggCbg222mUzK%2Fx0E%2BVt3k67kiBOASpQFjq63FErchpj61DrFdXsT7eKMcGaqs%2BofB0vXLnwwdAjJ3n4vQm%2FSeT3onZpfU1F4lkq8CAXje8db0Gbn6lcVV4y1ULRfryswkqhVR500Mxjb4%2B4EXKmzU51nTkE1uqkMrKLibZjBGHa91sEbMUoqfKbzveKF0k2ksX24Uff44wQweoj7%2FQtY1PyRbtvixZ6%2BYJ3gqx5qtadyFQJPSX0oDfvNFa%2BQVipfvR7ua5uahf3gdA9bngCMGcWA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 11:07:40,461 INFO    Thread-17 :102694 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_110735-vv9iv6jn/files/output.log
2023-07-11 11:07:41,311 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:07:42,462 INFO    Thread-17 :102694 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_110735-vv9iv6jn/files/output.log
2023-07-11 11:07:46,515 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:07:49,512 DEBUG   SenderThread:102694 [sender.py:send():369] send: telemetry
2023-07-11 11:07:50,464 INFO    Thread-17 :102694 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_110735-vv9iv6jn/files/output.log
2023-07-11 11:07:51,579 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:07:52,677 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 11:07:52,678 DEBUG   SenderThread:102694 [sender.py:send_request():396] send_request: stop_status
2023-07-11 11:07:56,466 INFO    Thread-17 :102694 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_110735-vv9iv6jn/files/output.log
2023-07-11 11:07:57,268 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:07:58,470 INFO    Thread-17 :102694 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_110735-vv9iv6jn/files/output.log
2023-07-11 11:08:02,297 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:08:07,306 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:08:07,682 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 11:08:07,682 DEBUG   SenderThread:102694 [sender.py:send_request():396] send_request: stop_status
2023-07-11 11:08:08,473 INFO    Thread-17 :102694 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_110735-vv9iv6jn/files/config.yaml
2023-07-11 11:08:12,937 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:08:17,938 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:08:22,682 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 11:08:22,683 DEBUG   SenderThread:102694 [sender.py:send_request():396] send_request: stop_status
2023-07-11 11:08:22,940 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:08:27,940 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:08:32,941 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:08:36,673 DEBUG   SystemMonitor:102694 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-11 11:08:36,674 DEBUG   SenderThread:102694 [sender.py:send():369] send: stats
2023-07-11 11:08:37,682 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 11:08:37,683 DEBUG   SenderThread:102694 [sender.py:send_request():396] send_request: stop_status
2023-07-11 11:08:38,931 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:08:43,932 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:08:48,933 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:08:52,682 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 11:08:52,683 DEBUG   SenderThread:102694 [sender.py:send_request():396] send_request: stop_status
2023-07-11 11:08:54,932 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:08:59,933 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:09:04,933 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:09:06,675 DEBUG   SenderThread:102694 [sender.py:send():369] send: stats
2023-07-11 11:09:07,683 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 11:09:07,683 DEBUG   SenderThread:102694 [sender.py:send_request():396] send_request: stop_status
2023-07-11 11:09:10,921 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:09:15,922 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:09:20,923 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 11:09:22,683 DEBUG   HandlerThread:102694 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 11:09:22,683 DEBUG   SenderThread:102694 [sender.py:send_request():396] send_request: stop_status
