2023-07-11 00:39:12,881 INFO    StreamThr :58249 [internal.py:wandb_internal():86] W&B internal server running at pid: 58249, started at: 2023-07-11 00:39:12.881454
2023-07-11 00:39:12,884 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status
2023-07-11 00:39:12,886 INFO    WriterThread:58249 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_003912-qfye6miw/run-qfye6miw.wandb
2023-07-11 00:39:12,888 DEBUG   SenderThread:58249 [sender.py:send():369] send: header
2023-07-11 00:39:12,888 DEBUG   SenderThread:58249 [sender.py:send():369] send: run
2023-07-11 00:39:13,806 INFO    SenderThread:58249 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_003912-qfye6miw/files
2023-07-11 00:39:13,806 INFO    SenderThread:58249 [sender.py:_start_run_threads():1100] run started: qfye6miw with start time 1689007152.880668
2023-07-11 00:39:13,808 DEBUG   SenderThread:58249 [sender.py:send_request():396] send_request: summary_record
2023-07-11 00:39:13,808 INFO    SenderThread:58249 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-11 00:39:13,814 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: check_version
2023-07-11 00:39:13,814 DEBUG   SenderThread:58249 [sender.py:send_request():396] send_request: check_version
2023-07-11 00:39:14,022 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: run_start
2023-07-11 00:39:14,032 DEBUG   HandlerThread:58249 [system_info.py:__init__():31] System info init
2023-07-11 00:39:14,032 DEBUG   HandlerThread:58249 [system_info.py:__init__():46] System info init done
2023-07-11 00:39:14,033 INFO    HandlerThread:58249 [system_monitor.py:start():181] Starting system monitor
2023-07-11 00:39:14,034 INFO    HandlerThread:58249 [system_monitor.py:probe():201] Collecting system info
2023-07-11 00:39:14,036 INFO    SystemMonitor:58249 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-11 00:39:14,041 INFO    SystemMonitor:58249 [interfaces.py:start():190] Started cpu monitoring
2023-07-11 00:39:14,043 INFO    SystemMonitor:58249 [interfaces.py:start():190] Started disk monitoring
2023-07-11 00:39:14,047 INFO    SystemMonitor:58249 [interfaces.py:start():190] Started gpu monitoring
2023-07-11 00:39:14,048 INFO    SystemMonitor:58249 [interfaces.py:start():190] Started memory monitoring
2023-07-11 00:39:14,051 INFO    SystemMonitor:58249 [interfaces.py:start():190] Started network monitoring
2023-07-11 00:39:14,071 DEBUG   HandlerThread:58249 [system_info.py:probe():195] Probing system
2023-07-11 00:39:14,078 DEBUG   HandlerThread:58249 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-11 00:39:14,078 DEBUG   HandlerThread:58249 [system_info.py:probe():240] Probing system done
2023-07-11 00:39:14,078 DEBUG   HandlerThread:58249 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T16:39:14.071433', 'startedAt': '2023-07-10T16:39:12.872119', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 1835.4283749999997, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 1100.35, 'min': 800.0, 'max': 5100.0}, {'current': 1100.324, 'min': 800.0, 'max': 5100.0}, {'current': 1100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1098.971, 'min': 800.0, 'max': 5100.0}, {'current': 2004.01, 'min': 800.0, 'max': 5100.0}, {'current': 1100.006, 'min': 800.0, 'max': 5200.0}, {'current': 1100.197, 'min': 800.0, 'max': 5200.0}, {'current': 1100.0, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 1100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1759.14, 'min': 800.0, 'max': 5100.0}, {'current': 1100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.01883697509765625}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-11 00:39:14,078 INFO    HandlerThread:58249 [system_monitor.py:probe():211] Finished collecting system info
2023-07-11 00:39:14,079 INFO    HandlerThread:58249 [system_monitor.py:probe():214] Publishing system info
2023-07-11 00:39:14,079 DEBUG   HandlerThread:58249 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-11 00:39:14,079 DEBUG   HandlerThread:58249 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-11 00:39:14,079 DEBUG   HandlerThread:58249 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-11 00:39:14,809 INFO    Thread-17 :58249 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_003912-qfye6miw/files/requirements.txt
2023-07-11 00:39:14,809 INFO    Thread-17 :58249 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_003912-qfye6miw/files/wandb-summary.json
2023-07-11 00:39:14,809 INFO    Thread-17 :58249 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_003912-qfye6miw/files/conda-environment.yaml
2023-07-11 00:39:14,961 DEBUG   HandlerThread:58249 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-11 00:39:14,963 INFO    HandlerThread:58249 [system_monitor.py:probe():216] Finished publishing system info
2023-07-11 00:39:14,965 DEBUG   SenderThread:58249 [sender.py:send():369] send: files
2023-07-11 00:39:14,965 INFO    SenderThread:58249 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-11 00:39:14,972 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 00:39:14,973 DEBUG   SenderThread:58249 [sender.py:send_request():396] send_request: stop_status
2023-07-11 00:39:15,431 ERROR   wandb-upload_0:58249 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/qfye6miw/wandb-metadata.json?Expires=1689093555&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v%2FL%2FXgVaBF1mIJ9LMFV6qlYOx3mgMrwvVq%2BUBmak3OplGzepoYnQJM7HZ9ex3eDvMfOvtTasuURjKpxseUt8Kvzmg6N0qIIv3T%2FXU2aKfhEXppo%2BnNXe09sFPQaW%2Bn1gD9I1kb6FcDkaUcQryTKBD24xQrFs8vWr8OH06h3q12YbEZTwcjHIdenwx7IFGDb0wAjylb0lE3a20aD75re%2B3y0LmZ51AWCM8ACxC0OvBfAiuPoQjxBET8NPDlkL5Vyx3tcLxZXfqNdNecKcvRY7Pkmt2QLbwXJVsQY6pr%2FyoF5lury1PCGQKmoCDEqMYWgF02xx3lMS7QofB1vWmAFrmw%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/qfye6miw/wandb-metadata.json?Expires=1689093555&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v%2FL%2FXgVaBF1mIJ9LMFV6qlYOx3mgMrwvVq%2BUBmak3OplGzepoYnQJM7HZ9ex3eDvMfOvtTasuURjKpxseUt8Kvzmg6N0qIIv3T%2FXU2aKfhEXppo%2BnNXe09sFPQaW%2Bn1gD9I1kb6FcDkaUcQryTKBD24xQrFs8vWr8OH06h3q12YbEZTwcjHIdenwx7IFGDb0wAjylb0lE3a20aD75re%2B3y0LmZ51AWCM8ACxC0OvBfAiuPoQjxBET8NPDlkL5Vyx3tcLxZXfqNdNecKcvRY7Pkmt2QLbwXJVsQY6pr%2FyoF5lury1PCGQKmoCDEqMYWgF02xx3lMS7QofB1vWmAFrmw%3D%3D
2023-07-11 00:39:15,431 ERROR   wandb-upload_0:58249 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3616'}
2023-07-11 00:39:15,431 ERROR   wandb-upload_0:58249 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/qfye6miw/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-11 00:39:15,539 DEBUG   SenderThread:58249 [sender.py:send():369] send: telemetry
2023-07-11 00:39:15,807 INFO    Thread-17 :58249 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_003912-qfye6miw/files/conda-environment.yaml
2023-07-11 00:39:15,807 INFO    Thread-17 :58249 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_003912-qfye6miw/files/wandb-metadata.json
2023-07-11 00:39:15,808 INFO    Thread-17 :58249 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_003912-qfye6miw/files/output.log
2023-07-11 00:39:17,436 ERROR   wandb-upload_0:58249 [upload_job.py:push():136] Failed to upload file: /tmp/tmpkap97v4_wandb/o01aimww-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/qfye6miw/wandb-metadata.json?Expires=1689093555&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v%2FL%2FXgVaBF1mIJ9LMFV6qlYOx3mgMrwvVq%2BUBmak3OplGzepoYnQJM7HZ9ex3eDvMfOvtTasuURjKpxseUt8Kvzmg6N0qIIv3T%2FXU2aKfhEXppo%2BnNXe09sFPQaW%2Bn1gD9I1kb6FcDkaUcQryTKBD24xQrFs8vWr8OH06h3q12YbEZTwcjHIdenwx7IFGDb0wAjylb0lE3a20aD75re%2B3y0LmZ51AWCM8ACxC0OvBfAiuPoQjxBET8NPDlkL5Vyx3tcLxZXfqNdNecKcvRY7Pkmt2QLbwXJVsQY6pr%2FyoF5lury1PCGQKmoCDEqMYWgF02xx3lMS7QofB1vWmAFrmw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 00:39:17,808 INFO    Thread-17 :58249 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_003912-qfye6miw/files/output.log
2023-07-11 00:39:18,000 ERROR   Thread-16 :58249 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpkap97v4_wandb/o01aimww-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/qfye6miw/wandb-metadata.json?Expires=1689093555&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v%2FL%2FXgVaBF1mIJ9LMFV6qlYOx3mgMrwvVq%2BUBmak3OplGzepoYnQJM7HZ9ex3eDvMfOvtTasuURjKpxseUt8Kvzmg6N0qIIv3T%2FXU2aKfhEXppo%2BnNXe09sFPQaW%2Bn1gD9I1kb6FcDkaUcQryTKBD24xQrFs8vWr8OH06h3q12YbEZTwcjHIdenwx7IFGDb0wAjylb0lE3a20aD75re%2B3y0LmZ51AWCM8ACxC0OvBfAiuPoQjxBET8NPDlkL5Vyx3tcLxZXfqNdNecKcvRY7Pkmt2QLbwXJVsQY6pr%2FyoF5lury1PCGQKmoCDEqMYWgF02xx3lMS7QofB1vWmAFrmw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 00:39:18,136 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:39:19,809 INFO    Thread-17 :58249 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_003912-qfye6miw/files/output.log
2023-07-11 00:39:23,350 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:39:25,516 DEBUG   SenderThread:58249 [sender.py:send():369] send: telemetry
2023-07-11 00:39:25,811 INFO    Thread-17 :58249 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_003912-qfye6miw/files/output.log
2023-07-11 00:39:27,811 INFO    Thread-17 :58249 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_003912-qfye6miw/files/output.log
2023-07-11 00:39:28,584 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:39:29,970 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 00:39:29,971 DEBUG   SenderThread:58249 [sender.py:send_request():396] send_request: stop_status
2023-07-11 00:39:31,656 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: partial_history
2023-07-11 00:39:31,813 INFO    Thread-17 :58249 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_003912-qfye6miw/files/output.log
2023-07-11 00:39:33,657 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:39:33,815 INFO    Thread-17 :58249 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_003912-qfye6miw/files/output.log
2023-07-11 00:39:38,659 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:39:43,666 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:39:44,824 INFO    Thread-17 :58249 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_003912-qfye6miw/files/config.yaml
2023-07-11 00:39:44,972 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 00:39:44,974 DEBUG   SenderThread:58249 [sender.py:send_request():396] send_request: stop_status
2023-07-11 00:39:49,224 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:39:54,226 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:39:59,227 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:39:59,972 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 00:39:59,973 DEBUG   SenderThread:58249 [sender.py:send_request():396] send_request: stop_status
2023-07-11 00:40:05,226 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:40:10,228 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:40:14,052 DEBUG   SystemMonitor:58249 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-11 00:40:14,056 DEBUG   SenderThread:58249 [sender.py:send():369] send: stats
2023-07-11 00:40:14,972 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 00:40:14,975 DEBUG   SenderThread:58249 [sender.py:send_request():396] send_request: stop_status
2023-07-11 00:40:15,278 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:40:20,279 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:40:25,280 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:40:29,973 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 00:40:29,975 DEBUG   SenderThread:58249 [sender.py:send_request():396] send_request: stop_status
2023-07-11 00:40:31,214 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:40:36,215 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:40:41,217 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:40:44,060 DEBUG   SenderThread:58249 [sender.py:send():369] send: stats
2023-07-11 00:40:44,972 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 00:40:44,973 DEBUG   SenderThread:58249 [sender.py:send_request():396] send_request: stop_status
2023-07-11 00:40:47,216 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:40:52,218 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:40:57,219 DEBUG   HandlerThread:58249 [handler.py:handle_request():144] handle_request: status_report
