2023-07-10 21:00:27,741 INFO    StreamThr :40302 [internal.py:wandb_internal():86] W&B internal server running at pid: 40302, started at: 2023-07-10 21:00:27.741017
2023-07-10 21:00:27,745 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status
2023-07-10 21:00:27,747 INFO    WriterThread:40302 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210027-6wnotn0l/run-6wnotn0l.wandb
2023-07-10 21:00:27,748 DEBUG   SenderThread:40302 [sender.py:send():369] send: header
2023-07-10 21:00:27,748 DEBUG   SenderThread:40302 [sender.py:send():369] send: run
2023-07-10 21:00:28,620 INFO    SenderThread:40302 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210027-6wnotn0l/files
2023-07-10 21:00:28,620 INFO    SenderThread:40302 [sender.py:_start_run_threads():1100] run started: 6wnotn0l with start time 1688994027.740192
2023-07-10 21:00:28,621 DEBUG   SenderThread:40302 [sender.py:send_request():396] send_request: summary_record
2023-07-10 21:00:28,621 INFO    SenderThread:40302 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 21:00:28,627 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 21:00:28,627 DEBUG   SenderThread:40302 [sender.py:send_request():396] send_request: check_version
2023-07-10 21:00:28,828 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 21:00:28,837 DEBUG   HandlerThread:40302 [system_info.py:__init__():31] System info init
2023-07-10 21:00:28,837 DEBUG   HandlerThread:40302 [system_info.py:__init__():46] System info init done
2023-07-10 21:00:28,837 INFO    HandlerThread:40302 [system_monitor.py:start():181] Starting system monitor
2023-07-10 21:00:28,838 INFO    HandlerThread:40302 [system_monitor.py:probe():201] Collecting system info
2023-07-10 21:00:28,838 INFO    SystemMonitor:40302 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 21:00:28,843 INFO    SystemMonitor:40302 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 21:00:28,845 INFO    SystemMonitor:40302 [interfaces.py:start():190] Started disk monitoring
2023-07-10 21:00:28,849 INFO    SystemMonitor:40302 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 21:00:28,852 INFO    SystemMonitor:40302 [interfaces.py:start():190] Started memory monitoring
2023-07-10 21:00:28,854 INFO    SystemMonitor:40302 [interfaces.py:start():190] Started network monitoring
2023-07-10 21:00:28,871 DEBUG   HandlerThread:40302 [system_info.py:probe():195] Probing system
2023-07-10 21:00:28,877 DEBUG   HandlerThread:40302 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 21:00:28,878 DEBUG   HandlerThread:40302 [system_info.py:probe():240] Probing system done
2023-07-10 21:00:28,878 DEBUG   HandlerThread:40302 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T13:00:28.872016', 'startedAt': '2023-07-10T13:00:27.731841', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 1785.7385416666666, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 1122.938, 'min': 800.0, 'max': 5100.0}, {'current': 1176.442, 'min': 800.0, 'max': 5100.0}, {'current': 1100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1441.897, 'min': 800.0, 'max': 5100.0}, {'current': 1224.521, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1114.352, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1099.661, 'min': 800.0, 'max': 5200.0}, {'current': 1099.081, 'min': 800.0, 'max': 5200.0}, {'current': 1113.291, 'min': 800.0, 'max': 5200.0}, {'current': 1121.179, 'min': 800.0, 'max': 5200.0}, {'current': 1168.908, 'min': 800.0, 'max': 5100.0}, {'current': 1247.586, 'min': 800.0, 'max': 5100.0}, {'current': 1228.213, 'min': 800.0, 'max': 5100.0}, {'current': 1228.987, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 975.857, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.018512725830078125}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-10 21:00:28,878 INFO    HandlerThread:40302 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 21:00:28,878 INFO    HandlerThread:40302 [system_monitor.py:probe():214] Publishing system info
2023-07-10 21:00:28,878 DEBUG   HandlerThread:40302 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 21:00:28,879 DEBUG   HandlerThread:40302 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 21:00:28,879 DEBUG   HandlerThread:40302 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 21:00:29,623 INFO    Thread-17 :40302 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210027-6wnotn0l/files/conda-environment.yaml
2023-07-10 21:00:29,624 INFO    Thread-17 :40302 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210027-6wnotn0l/files/wandb-summary.json
2023-07-10 21:00:29,624 INFO    Thread-17 :40302 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210027-6wnotn0l/files/requirements.txt
2023-07-10 21:00:29,754 DEBUG   HandlerThread:40302 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 21:00:29,755 INFO    HandlerThread:40302 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 21:00:29,758 DEBUG   SenderThread:40302 [sender.py:send():369] send: files
2023-07-10 21:00:29,758 INFO    SenderThread:40302 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 21:00:29,764 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:00:29,765 DEBUG   SenderThread:40302 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:00:30,233 ERROR   wandb-upload_0:40302 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/6wnotn0l/wandb-metadata.json?Expires=1689080429&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o2CObEDZqv6JE5lIkalaXGQDGQ1q0c1R1sGQLzXorXNDnep7OyHVGX26IpMhiBVUakrA9fJ3ZzfhzQnaEGJXbk1SBlWZbdluvVBTjbfz%2BflrnAVg8FTtr7dPAor3MA0P1VIE1dtzaSteYPrKiOrwGQlsxCxdW%2Fgc40BWUe224KKTaOjKyn00IqJV4xHblUFFJNcmhHaAzNR5cxpbc8Exe6U30uhC8EQHRrDhmalNGH1YZiJ%2B82Y7HIKegDgUpBOoz%2BxuzvYdAudf6VGqeAmIRcNB11d%2F%2FYPL6S%2B%2Fcb9v%2BuJqKmJPQS0%2B5Ya9%2FwrZqHZuFcbfQ3qveeF1Ax4E%2Fgg0%2Fg%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/6wnotn0l/wandb-metadata.json?Expires=1689080429&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o2CObEDZqv6JE5lIkalaXGQDGQ1q0c1R1sGQLzXorXNDnep7OyHVGX26IpMhiBVUakrA9fJ3ZzfhzQnaEGJXbk1SBlWZbdluvVBTjbfz%2BflrnAVg8FTtr7dPAor3MA0P1VIE1dtzaSteYPrKiOrwGQlsxCxdW%2Fgc40BWUe224KKTaOjKyn00IqJV4xHblUFFJNcmhHaAzNR5cxpbc8Exe6U30uhC8EQHRrDhmalNGH1YZiJ%2B82Y7HIKegDgUpBOoz%2BxuzvYdAudf6VGqeAmIRcNB11d%2F%2FYPL6S%2B%2Fcb9v%2BuJqKmJPQS0%2B5Ya9%2FwrZqHZuFcbfQ3qveeF1Ax4E%2Fgg0%2Fg%3D%3D
2023-07-10 21:00:30,233 ERROR   wandb-upload_0:40302 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3633'}
2023-07-10 21:00:30,233 ERROR   wandb-upload_0:40302 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/6wnotn0l/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 21:00:30,369 DEBUG   SenderThread:40302 [sender.py:send():369] send: telemetry
2023-07-10 21:00:30,621 INFO    Thread-17 :40302 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210027-6wnotn0l/files/conda-environment.yaml
2023-07-10 21:00:30,621 INFO    Thread-17 :40302 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210027-6wnotn0l/files/wandb-metadata.json
2023-07-10 21:00:30,621 INFO    Thread-17 :40302 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210027-6wnotn0l/files/output.log
2023-07-10 21:00:32,238 ERROR   wandb-upload_0:40302 [upload_job.py:push():136] Failed to upload file: /tmp/tmp41rfmq2swandb/4suvdtb6-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/6wnotn0l/wandb-metadata.json?Expires=1689080429&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o2CObEDZqv6JE5lIkalaXGQDGQ1q0c1R1sGQLzXorXNDnep7OyHVGX26IpMhiBVUakrA9fJ3ZzfhzQnaEGJXbk1SBlWZbdluvVBTjbfz%2BflrnAVg8FTtr7dPAor3MA0P1VIE1dtzaSteYPrKiOrwGQlsxCxdW%2Fgc40BWUe224KKTaOjKyn00IqJV4xHblUFFJNcmhHaAzNR5cxpbc8Exe6U30uhC8EQHRrDhmalNGH1YZiJ%2B82Y7HIKegDgUpBOoz%2BxuzvYdAudf6VGqeAmIRcNB11d%2F%2FYPL6S%2B%2Fcb9v%2BuJqKmJPQS0%2B5Ya9%2FwrZqHZuFcbfQ3qveeF1Ax4E%2Fgg0%2Fg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 21:00:32,621 INFO    Thread-17 :40302 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210027-6wnotn0l/files/output.log
2023-07-10 21:00:33,003 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:00:34,245 ERROR   Thread-16 :40302 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmp41rfmq2swandb/4suvdtb6-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/6wnotn0l/wandb-metadata.json?Expires=1689080429&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=o2CObEDZqv6JE5lIkalaXGQDGQ1q0c1R1sGQLzXorXNDnep7OyHVGX26IpMhiBVUakrA9fJ3ZzfhzQnaEGJXbk1SBlWZbdluvVBTjbfz%2BflrnAVg8FTtr7dPAor3MA0P1VIE1dtzaSteYPrKiOrwGQlsxCxdW%2Fgc40BWUe224KKTaOjKyn00IqJV4xHblUFFJNcmhHaAzNR5cxpbc8Exe6U30uhC8EQHRrDhmalNGH1YZiJ%2B82Y7HIKegDgUpBOoz%2BxuzvYdAudf6VGqeAmIRcNB11d%2F%2FYPL6S%2B%2Fcb9v%2BuJqKmJPQS0%2B5Ya9%2FwrZqHZuFcbfQ3qveeF1Ax4E%2Fgg0%2Fg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 21:00:34,622 INFO    Thread-17 :40302 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210027-6wnotn0l/files/output.log
2023-07-10 21:00:38,207 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:00:40,605 DEBUG   SenderThread:40302 [sender.py:send():369] send: telemetry
2023-07-10 21:00:42,625 INFO    Thread-17 :40302 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210027-6wnotn0l/files/output.log
2023-07-10 21:00:43,671 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:00:44,764 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:00:44,764 DEBUG   SenderThread:40302 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:00:46,627 INFO    Thread-17 :40302 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210027-6wnotn0l/files/output.log
2023-07-10 21:00:46,982 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 21:00:48,629 INFO    Thread-17 :40302 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210027-6wnotn0l/files/output.log
2023-07-10 21:00:49,201 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:00:54,202 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:00:59,209 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:00:59,637 INFO    Thread-17 :40302 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210027-6wnotn0l/files/config.yaml
2023-07-10 21:00:59,766 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:00:59,769 DEBUG   SenderThread:40302 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:01:05,013 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:01:10,014 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:01:14,766 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:01:14,768 DEBUG   SenderThread:40302 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:01:15,024 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:01:20,025 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:01:25,026 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:01:28,855 DEBUG   SystemMonitor:40302 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-10 21:01:28,860 DEBUG   SenderThread:40302 [sender.py:send():369] send: stats
2023-07-10 21:01:29,766 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:01:29,769 DEBUG   SenderThread:40302 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:01:31,014 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:01:36,015 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:01:41,016 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:01:44,768 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:01:44,770 DEBUG   SenderThread:40302 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:01:46,025 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:01:51,027 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:01:56,028 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:01:58,860 DEBUG   SenderThread:40302 [sender.py:send():369] send: stats
2023-07-10 21:01:59,767 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:01:59,770 DEBUG   SenderThread:40302 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:02:01,029 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:02:06,031 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:02:11,032 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:02:14,768 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:02:14,770 DEBUG   SenderThread:40302 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:02:17,024 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:02:22,025 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:02:27,027 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:02:28,865 DEBUG   SenderThread:40302 [sender.py:send():369] send: stats
2023-07-10 21:02:29,768 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:02:29,770 DEBUG   SenderThread:40302 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:02:33,026 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:02:38,027 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:02:43,028 DEBUG   HandlerThread:40302 [handler.py:handle_request():144] handle_request: status_report
