2023-07-11 00:41:04,006 INFO    StreamThr :58711 [internal.py:wandb_internal():86] W&B internal server running at pid: 58711, started at: 2023-07-11 00:41:04.005873
2023-07-11 00:41:04,009 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: status
2023-07-11 00:41:04,012 INFO    WriterThread:58711 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_004103-to5smkyk/run-to5smkyk.wandb
2023-07-11 00:41:04,012 DEBUG   SenderThread:58711 [sender.py:send():369] send: header
2023-07-11 00:41:04,012 DEBUG   SenderThread:58711 [sender.py:send():369] send: run
2023-07-11 00:41:04,877 INFO    SenderThread:58711 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_004103-to5smkyk/files
2023-07-11 00:41:04,877 INFO    SenderThread:58711 [sender.py:_start_run_threads():1100] run started: to5smkyk with start time 1689007264.005015
2023-07-11 00:41:04,877 DEBUG   SenderThread:58711 [sender.py:send_request():396] send_request: summary_record
2023-07-11 00:41:04,878 INFO    SenderThread:58711 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-11 00:41:04,883 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: check_version
2023-07-11 00:41:04,883 DEBUG   SenderThread:58711 [sender.py:send_request():396] send_request: check_version
2023-07-11 00:41:05,085 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: run_start
2023-07-11 00:41:05,095 DEBUG   HandlerThread:58711 [system_info.py:__init__():31] System info init
2023-07-11 00:41:05,095 DEBUG   HandlerThread:58711 [system_info.py:__init__():46] System info init done
2023-07-11 00:41:05,096 INFO    HandlerThread:58711 [system_monitor.py:start():181] Starting system monitor
2023-07-11 00:41:05,097 INFO    HandlerThread:58711 [system_monitor.py:probe():201] Collecting system info
2023-07-11 00:41:05,097 INFO    SystemMonitor:58711 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-11 00:41:05,099 INFO    SystemMonitor:58711 [interfaces.py:start():190] Started cpu monitoring
2023-07-11 00:41:05,102 INFO    SystemMonitor:58711 [interfaces.py:start():190] Started disk monitoring
2023-07-11 00:41:05,107 INFO    SystemMonitor:58711 [interfaces.py:start():190] Started gpu monitoring
2023-07-11 00:41:05,109 INFO    SystemMonitor:58711 [interfaces.py:start():190] Started memory monitoring
2023-07-11 00:41:05,111 INFO    SystemMonitor:58711 [interfaces.py:start():190] Started network monitoring
2023-07-11 00:41:05,122 DEBUG   HandlerThread:58711 [system_info.py:probe():195] Probing system
2023-07-11 00:41:05,126 DEBUG   HandlerThread:58711 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-11 00:41:05,126 DEBUG   HandlerThread:58711 [system_info.py:probe():240] Probing system done
2023-07-11 00:41:05,126 DEBUG   HandlerThread:58711 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T16:41:05.122087', 'startedAt': '2023-07-10T16:41:03.996832', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 1859.9804166666665, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 2382.303, 'min': 800.0, 'max': 5100.0}, {'current': 1658.031, 'min': 800.0, 'max': 5100.0}, {'current': 2233.963, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1995.473, 'min': 800.0, 'max': 5100.0}, {'current': 1812.558, 'min': 800.0, 'max': 5100.0}, {'current': 2026.194, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2296.604, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 3245.243, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 1852.63, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 4932.328, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1390.044, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 1279.572, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.0188751220703125}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-11 00:41:05,127 INFO    HandlerThread:58711 [system_monitor.py:probe():211] Finished collecting system info
2023-07-11 00:41:05,127 INFO    HandlerThread:58711 [system_monitor.py:probe():214] Publishing system info
2023-07-11 00:41:05,127 DEBUG   HandlerThread:58711 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-11 00:41:05,127 DEBUG   HandlerThread:58711 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-11 00:41:05,127 DEBUG   HandlerThread:58711 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-11 00:41:05,880 INFO    Thread-17 :58711 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_004103-to5smkyk/files/requirements.txt
2023-07-11 00:41:05,880 INFO    Thread-17 :58711 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_004103-to5smkyk/files/conda-environment.yaml
2023-07-11 00:41:05,880 INFO    Thread-17 :58711 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_004103-to5smkyk/files/wandb-summary.json
2023-07-11 00:41:06,010 DEBUG   HandlerThread:58711 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-11 00:41:06,011 INFO    HandlerThread:58711 [system_monitor.py:probe():216] Finished publishing system info
2023-07-11 00:41:06,015 DEBUG   SenderThread:58711 [sender.py:send():369] send: files
2023-07-11 00:41:06,015 INFO    SenderThread:58711 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-11 00:41:06,021 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 00:41:06,021 DEBUG   SenderThread:58711 [sender.py:send_request():396] send_request: stop_status
2023-07-11 00:41:06,266 DEBUG   SenderThread:58711 [sender.py:send():369] send: telemetry
2023-07-11 00:41:06,851 ERROR   wandb-upload_0:58711 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/to5smkyk/wandb-metadata.json?Expires=1689093666&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NVGkibY0l2LR%2BbdXc4H55FlM0mKNahofojJvxUclG%2FnlBloDxrQjL2BOMh2PnsNNHHpLseGz3qI5b6Oel1qy5mruUEN7QbX1D6MaAyUSKCgVnBdAz%2BlTVNrTITbHUZjC8Ql4atUVeMn%2BGzLk%2BHv3X0%2BEUZG7I53ETS3q3VnL7MhoafcKh8Rz3ATwh2KU06LeGO4REwhsT2OeGZq5PRTf9D5Ah0KdTniavWMqqzwN1a3k7TPBm4GuRnEhymH4NAiVWhT%2BKDlnRzScHc2Ws%2FhtJ54lf9nSoiKbLYG7preALJkKeSXludneDHAsRBY0iscAeU25loNc7Bd7THBFR46Tyw%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/to5smkyk/wandb-metadata.json?Expires=1689093666&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NVGkibY0l2LR%2BbdXc4H55FlM0mKNahofojJvxUclG%2FnlBloDxrQjL2BOMh2PnsNNHHpLseGz3qI5b6Oel1qy5mruUEN7QbX1D6MaAyUSKCgVnBdAz%2BlTVNrTITbHUZjC8Ql4atUVeMn%2BGzLk%2BHv3X0%2BEUZG7I53ETS3q3VnL7MhoafcKh8Rz3ATwh2KU06LeGO4REwhsT2OeGZq5PRTf9D5Ah0KdTniavWMqqzwN1a3k7TPBm4GuRnEhymH4NAiVWhT%2BKDlnRzScHc2Ws%2FhtJ54lf9nSoiKbLYG7preALJkKeSXludneDHAsRBY0iscAeU25loNc7Bd7THBFR46Tyw%3D%3D
2023-07-11 00:41:06,851 ERROR   wandb-upload_0:58711 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3627'}
2023-07-11 00:41:06,851 ERROR   wandb-upload_0:58711 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/to5smkyk/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-11 00:41:06,880 INFO    Thread-17 :58711 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_004103-to5smkyk/files/conda-environment.yaml
2023-07-11 00:41:06,880 INFO    Thread-17 :58711 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_004103-to5smkyk/files/output.log
2023-07-11 00:41:06,881 INFO    Thread-17 :58711 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_004103-to5smkyk/files/wandb-metadata.json
2023-07-11 00:41:07,401 ERROR   wandb-upload_0:58711 [upload_job.py:push():136] Failed to upload file: /tmp/tmp1sz3v9zawandb/exbbfyz8-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/to5smkyk/wandb-metadata.json?Expires=1689093666&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NVGkibY0l2LR%2BbdXc4H55FlM0mKNahofojJvxUclG%2FnlBloDxrQjL2BOMh2PnsNNHHpLseGz3qI5b6Oel1qy5mruUEN7QbX1D6MaAyUSKCgVnBdAz%2BlTVNrTITbHUZjC8Ql4atUVeMn%2BGzLk%2BHv3X0%2BEUZG7I53ETS3q3VnL7MhoafcKh8Rz3ATwh2KU06LeGO4REwhsT2OeGZq5PRTf9D5Ah0KdTniavWMqqzwN1a3k7TPBm4GuRnEhymH4NAiVWhT%2BKDlnRzScHc2Ws%2FhtJ54lf9nSoiKbLYG7preALJkKeSXludneDHAsRBY0iscAeU25loNc7Bd7THBFR46Tyw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 00:41:07,617 ERROR   Thread-16 :58711 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmp1sz3v9zawandb/exbbfyz8-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/to5smkyk/wandb-metadata.json?Expires=1689093666&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NVGkibY0l2LR%2BbdXc4H55FlM0mKNahofojJvxUclG%2FnlBloDxrQjL2BOMh2PnsNNHHpLseGz3qI5b6Oel1qy5mruUEN7QbX1D6MaAyUSKCgVnBdAz%2BlTVNrTITbHUZjC8Ql4atUVeMn%2BGzLk%2BHv3X0%2BEUZG7I53ETS3q3VnL7MhoafcKh8Rz3ATwh2KU06LeGO4REwhsT2OeGZq5PRTf9D5Ah0KdTniavWMqqzwN1a3k7TPBm4GuRnEhymH4NAiVWhT%2BKDlnRzScHc2Ws%2FhtJ54lf9nSoiKbLYG7preALJkKeSXludneDHAsRBY0iscAeU25loNc7Bd7THBFR46Tyw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 00:41:08,881 INFO    Thread-17 :58711 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_004103-to5smkyk/files/output.log
2023-07-11 00:41:09,190 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:41:10,881 INFO    Thread-17 :58711 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_004103-to5smkyk/files/output.log
2023-07-11 00:41:14,401 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:41:16,726 DEBUG   SenderThread:58711 [sender.py:send():369] send: telemetry
2023-07-11 00:41:18,884 INFO    Thread-17 :58711 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_004103-to5smkyk/files/output.log
2023-07-11 00:41:19,793 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:41:21,019 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 00:41:21,020 DEBUG   SenderThread:58711 [sender.py:send_request():396] send_request: stop_status
2023-07-11 00:41:22,844 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: partial_history
2023-07-11 00:41:22,885 INFO    Thread-17 :58711 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_004103-to5smkyk/files/output.log
2023-07-11 00:41:24,845 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:41:24,887 INFO    Thread-17 :58711 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_004103-to5smkyk/files/output.log
2023-07-11 00:41:29,847 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:41:34,854 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:41:35,896 INFO    Thread-17 :58711 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_004103-to5smkyk/files/config.yaml
2023-07-11 00:41:36,021 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 00:41:36,022 DEBUG   SenderThread:58711 [sender.py:send_request():396] send_request: stop_status
2023-07-11 00:41:40,280 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:41:45,282 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:41:50,284 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:41:51,021 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 00:41:51,023 DEBUG   SenderThread:58711 [sender.py:send_request():396] send_request: stop_status
2023-07-11 00:41:56,259 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:42:01,261 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:42:05,111 DEBUG   SystemMonitor:58711 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-11 00:42:05,116 DEBUG   SenderThread:58711 [sender.py:send():369] send: stats
2023-07-11 00:42:06,022 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 00:42:06,023 DEBUG   SenderThread:58711 [sender.py:send_request():396] send_request: stop_status
2023-07-11 00:42:06,264 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:42:11,265 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 00:42:16,267 DEBUG   HandlerThread:58711 [handler.py:handle_request():144] handle_request: status_report
