2023-07-10 18:41:09,698 INFO    StreamThr :19718 [internal.py:wandb_internal():86] W&B internal server running at pid: 19718, started at: 2023-07-10 18:41:09.697808
2023-07-10 18:41:09,701 DEBUG   HandlerThread:19718 [handler.py:handle_request():144] handle_request: status
2023-07-10 18:41:09,703 INFO    WriterThread:19718 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/run-jzv6vou5.wandb
2023-07-10 18:41:09,704 DEBUG   SenderThread:19718 [sender.py:send():369] send: header
2023-07-10 18:41:09,704 DEBUG   SenderThread:19718 [sender.py:send():369] send: run
2023-07-10 18:41:10,581 INFO    SenderThread:19718 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files
2023-07-10 18:41:10,581 INFO    SenderThread:19718 [sender.py:_start_run_threads():1100] run started: jzv6vou5 with start time 1688985669.696921
2023-07-10 18:41:10,582 DEBUG   SenderThread:19718 [sender.py:send_request():396] send_request: summary_record
2023-07-10 18:41:10,583 INFO    SenderThread:19718 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 18:41:10,589 DEBUG   HandlerThread:19718 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 18:41:10,589 DEBUG   SenderThread:19718 [sender.py:send_request():396] send_request: check_version
2023-07-10 18:41:10,772 DEBUG   HandlerThread:19718 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 18:41:10,776 DEBUG   HandlerThread:19718 [system_info.py:__init__():31] System info init
2023-07-10 18:41:10,776 DEBUG   HandlerThread:19718 [system_info.py:__init__():46] System info init done
2023-07-10 18:41:10,777 INFO    HandlerThread:19718 [system_monitor.py:start():181] Starting system monitor
2023-07-10 18:41:10,777 INFO    HandlerThread:19718 [system_monitor.py:probe():201] Collecting system info
2023-07-10 18:41:10,777 INFO    SystemMonitor:19718 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 18:41:10,779 INFO    SystemMonitor:19718 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 18:41:10,780 INFO    SystemMonitor:19718 [interfaces.py:start():190] Started disk monitoring
2023-07-10 18:41:10,781 INFO    SystemMonitor:19718 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 18:41:10,782 INFO    SystemMonitor:19718 [interfaces.py:start():190] Started memory monitoring
2023-07-10 18:41:10,782 INFO    SystemMonitor:19718 [interfaces.py:start():190] Started network monitoring
2023-07-10 18:41:10,797 DEBUG   HandlerThread:19718 [system_info.py:probe():195] Probing system
2023-07-10 18:41:10,801 DEBUG   HandlerThread:19718 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 18:41:10,801 DEBUG   HandlerThread:19718 [system_info.py:probe():240] Probing system done
2023-07-10 18:41:10,801 DEBUG   HandlerThread:19718 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T10:41:10.797637', 'startedAt': '2023-07-10T10:41:09.689392', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 4047.6737916666666, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 5099.982, 'min': 800.0, 'max': 5100.0}, {'current': 5100.301, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5115.692, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5099.909, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 4976.136, 'min': 800.0, 'max': 5200.0}, {'current': 5100.012, 'min': 800.0, 'max': 5200.0}, {'current': 5153.282, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5105.437, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 4809.858, 'min': 800.0, 'max': 5100.0}, {'current': 3699.733, 'min': 800.0, 'max': 4100.0}, {'current': 3700.004, 'min': 800.0, 'max': 4100.0}, {'current': 3707.442, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.0179901123046875}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-10 18:41:10,801 INFO    HandlerThread:19718 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 18:41:10,801 INFO    HandlerThread:19718 [system_monitor.py:probe():214] Publishing system info
2023-07-10 18:41:10,801 DEBUG   HandlerThread:19718 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 18:41:10,801 DEBUG   HandlerThread:19718 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 18:41:10,801 DEBUG   HandlerThread:19718 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 18:41:11,586 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/requirements.txt
2023-07-10 18:41:11,586 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/conda-environment.yaml
2023-07-10 18:41:11,586 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/wandb-summary.json
2023-07-10 18:41:11,596 DEBUG   HandlerThread:19718 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 18:41:11,598 INFO    HandlerThread:19718 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 18:41:11,600 DEBUG   SenderThread:19718 [sender.py:send():369] send: files
2023-07-10 18:41:11,600 INFO    SenderThread:19718 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 18:41:11,606 DEBUG   HandlerThread:19718 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 18:41:11,607 DEBUG   SenderThread:19718 [sender.py:send_request():396] send_request: stop_status
2023-07-10 18:41:12,070 ERROR   wandb-upload_0:19718 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/jzv6vou5/wandb-metadata.json?Expires=1689072071&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=sfWsUD38DgJM1RA7SxsCZWP84IAO5Qf995mhZQuwOJIa%2FdkP16ixP%2FwElZk6JwEL32dsKk%2Fr%2BZnS3Xd66w0xk6uiK9IrTniXypU1MjDEqMT2GV1TC4JAK1k%2B0rLXcEifMeYyadQ3sGtC6GfJgyUTJM9LIxVKuk0B52FfIHqmcRJ%2FzApYdfkHA4gjcYf4DzaTyXJ9zfPk9wrRNvoYo28IXVX5HrdHTGeiCYH%2BMY9ndRuMakxzcamwMVVsM6QWmOylpc8RFWrOxBD2t34rMo54Cwh8JZGcbC8Y1%2BICLs%2FEPIMFbPi39rqXBiSb6Q9Ki1UqfHzmpMO7yu5TBg%2B5En1y3w%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/jzv6vou5/wandb-metadata.json?Expires=1689072071&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=sfWsUD38DgJM1RA7SxsCZWP84IAO5Qf995mhZQuwOJIa%2FdkP16ixP%2FwElZk6JwEL32dsKk%2Fr%2BZnS3Xd66w0xk6uiK9IrTniXypU1MjDEqMT2GV1TC4JAK1k%2B0rLXcEifMeYyadQ3sGtC6GfJgyUTJM9LIxVKuk0B52FfIHqmcRJ%2FzApYdfkHA4gjcYf4DzaTyXJ9zfPk9wrRNvoYo28IXVX5HrdHTGeiCYH%2BMY9ndRuMakxzcamwMVVsM6QWmOylpc8RFWrOxBD2t34rMo54Cwh8JZGcbC8Y1%2BICLs%2FEPIMFbPi39rqXBiSb6Q9Ki1UqfHzmpMO7yu5TBg%2B5En1y3w%3D%3D
2023-07-10 18:41:12,070 ERROR   wandb-upload_0:19718 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3628'}
2023-07-10 18:41:12,070 ERROR   wandb-upload_0:19718 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/jzv6vou5/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 18:41:12,197 DEBUG   SenderThread:19718 [sender.py:send():369] send: telemetry
2023-07-10 18:41:12,582 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/wandb-metadata.json
2023-07-10 18:41:12,583 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/output.log
2023-07-10 18:41:12,604 ERROR   wandb-upload_0:19718 [upload_job.py:push():136] Failed to upload file: /tmp/tmpa7ynb8n3wandb/hlxeb8nz-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/jzv6vou5/wandb-metadata.json?Expires=1689072071&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=sfWsUD38DgJM1RA7SxsCZWP84IAO5Qf995mhZQuwOJIa%2FdkP16ixP%2FwElZk6JwEL32dsKk%2Fr%2BZnS3Xd66w0xk6uiK9IrTniXypU1MjDEqMT2GV1TC4JAK1k%2B0rLXcEifMeYyadQ3sGtC6GfJgyUTJM9LIxVKuk0B52FfIHqmcRJ%2FzApYdfkHA4gjcYf4DzaTyXJ9zfPk9wrRNvoYo28IXVX5HrdHTGeiCYH%2BMY9ndRuMakxzcamwMVVsM6QWmOylpc8RFWrOxBD2t34rMo54Cwh8JZGcbC8Y1%2BICLs%2FEPIMFbPi39rqXBiSb6Q9Ki1UqfHzmpMO7yu5TBg%2B5En1y3w%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 18:41:12,816 ERROR   Thread-16 :19718 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpa7ynb8n3wandb/hlxeb8nz-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/jzv6vou5/wandb-metadata.json?Expires=1689072071&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=sfWsUD38DgJM1RA7SxsCZWP84IAO5Qf995mhZQuwOJIa%2FdkP16ixP%2FwElZk6JwEL32dsKk%2Fr%2BZnS3Xd66w0xk6uiK9IrTniXypU1MjDEqMT2GV1TC4JAK1k%2B0rLXcEifMeYyadQ3sGtC6GfJgyUTJM9LIxVKuk0B52FfIHqmcRJ%2FzApYdfkHA4gjcYf4DzaTyXJ9zfPk9wrRNvoYo28IXVX5HrdHTGeiCYH%2BMY9ndRuMakxzcamwMVVsM6QWmOylpc8RFWrOxBD2t34rMo54Cwh8JZGcbC8Y1%2BICLs%2FEPIMFbPi39rqXBiSb6Q9Ki1UqfHzmpMO7yu5TBg%2B5En1y3w%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 18:41:14,583 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/output.log
2023-07-10 18:41:14,754 DEBUG   HandlerThread:19718 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:41:16,673 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/output.log
2023-07-10 18:41:18,946 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/output.log
2023-07-10 18:41:22,348 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/output.log
2023-07-10 18:41:23,800 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/output.log
2023-07-10 18:41:24,342 DEBUG   HandlerThread:19718 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:41:26,281 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/output.log
2023-07-10 18:41:28,609 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/output.log
2023-07-10 18:41:31,099 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/output.log
2023-07-10 18:41:33,221 DEBUG   HandlerThread:19718 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:41:34,196 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/output.log
2023-07-10 18:41:35,496 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/output.log
2023-07-10 18:41:37,504 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/output.log
2023-07-10 18:41:39,574 DEBUG   HandlerThread:19718 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:41:40,613 INFO    Thread-17 :19718 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184109-jzv6vou5/files/config.yaml
