2023-07-10 15:37:26,414 INFO    StreamThr :45354 [internal.py:wandb_internal():86] W&B internal server running at pid: 45354, started at: 2023-07-10 15:37:26.414406
2023-07-10 15:37:26,417 DEBUG   HandlerThread:45354 [handler.py:handle_request():144] handle_request: status
2023-07-10 15:37:26,419 INFO    WriterThread:45354 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_153726-m21379as/run-m21379as.wandb
2023-07-10 15:37:26,423 DEBUG   SenderThread:45354 [sender.py:send():369] send: header
2023-07-10 15:37:26,423 DEBUG   SenderThread:45354 [sender.py:send():369] send: run
2023-07-10 15:37:27,284 INFO    SenderThread:45354 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_153726-m21379as/files
2023-07-10 15:37:27,285 INFO    SenderThread:45354 [sender.py:_start_run_threads():1100] run started: m21379as with start time 1688974646.413694
2023-07-10 15:37:27,285 DEBUG   SenderThread:45354 [sender.py:send_request():396] send_request: summary_record
2023-07-10 15:37:27,285 INFO    SenderThread:45354 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 15:37:27,290 DEBUG   HandlerThread:45354 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 15:37:27,290 DEBUG   SenderThread:45354 [sender.py:send_request():396] send_request: check_version
2023-07-10 15:37:27,476 DEBUG   HandlerThread:45354 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 15:37:27,481 DEBUG   HandlerThread:45354 [system_info.py:__init__():31] System info init
2023-07-10 15:37:27,481 DEBUG   HandlerThread:45354 [system_info.py:__init__():46] System info init done
2023-07-10 15:37:27,481 INFO    HandlerThread:45354 [system_monitor.py:start():181] Starting system monitor
2023-07-10 15:37:27,481 INFO    HandlerThread:45354 [system_monitor.py:probe():201] Collecting system info
2023-07-10 15:37:27,482 INFO    SystemMonitor:45354 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 15:37:27,484 INFO    SystemMonitor:45354 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 15:37:27,485 INFO    SystemMonitor:45354 [interfaces.py:start():190] Started disk monitoring
2023-07-10 15:37:27,486 INFO    SystemMonitor:45354 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 15:37:27,487 INFO    SystemMonitor:45354 [interfaces.py:start():190] Started memory monitoring
2023-07-10 15:37:27,489 INFO    SystemMonitor:45354 [interfaces.py:start():190] Started network monitoring
2023-07-10 15:37:27,499 DEBUG   HandlerThread:45354 [system_info.py:probe():195] Probing system
2023-07-10 15:37:27,507 DEBUG   HandlerThread:45354 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 15:37:27,509 DEBUG   HandlerThread:45354 [system_info.py:probe():240] Probing system done
2023-07-10 15:37:27,509 DEBUG   HandlerThread:45354 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T07:37:27.500073', 'startedAt': '2023-07-10T07:37:26.405472', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3646.01075, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 5099.456, 'min': 800.0, 'max': 5100.0}, {'current': 5099.885, 'min': 800.0, 'max': 5100.0}, {'current': 5099.866, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.044, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 4848.801, 'min': 800.0, 'max': 5200.0}, {'current': 5041.178, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 3700.384, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.018402099609375}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185562133789062}}
2023-07-10 15:37:27,509 INFO    HandlerThread:45354 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 15:37:27,509 INFO    HandlerThread:45354 [system_monitor.py:probe():214] Publishing system info
2023-07-10 15:37:27,509 DEBUG   HandlerThread:45354 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 15:37:27,509 DEBUG   HandlerThread:45354 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 15:37:27,509 DEBUG   HandlerThread:45354 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 15:37:28,287 INFO    Thread-17 :45354 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_153726-m21379as/files/wandb-summary.json
2023-07-10 15:37:28,288 INFO    Thread-17 :45354 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_153726-m21379as/files/conda-environment.yaml
2023-07-10 15:37:28,288 INFO    Thread-17 :45354 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_153726-m21379as/files/requirements.txt
2023-07-10 15:37:28,371 DEBUG   HandlerThread:45354 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 15:37:28,372 INFO    HandlerThread:45354 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 15:37:28,375 DEBUG   SenderThread:45354 [sender.py:send():369] send: files
2023-07-10 15:37:28,375 INFO    SenderThread:45354 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 15:37:28,381 DEBUG   HandlerThread:45354 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 15:37:28,382 DEBUG   SenderThread:45354 [sender.py:send_request():396] send_request: stop_status
2023-07-10 15:37:28,865 ERROR   wandb-upload_0:45354 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/m21379as/wandb-metadata.json?Expires=1689061048&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=EFp%2F4XeatmQPDNuViZEytbb7tXeVXXc%2FjOoGPWh0s0RHsw2lcHrwYYnOr8e2iSqAgph248bTgvyHvPj9NG5wtqzPcE8%2F2e5lFLvRL3J1fZ3AqvOfzDDasdl7Tpv8hHaJo3lWicNR1Xxc37ROd%2FcpRMkImhLMMGYNkHaWvGXYTmlLTfYEe2GXG2ugkdd0uEw7xk1Qu33kTaxE2cCH0u7DL8oc%2BeC3mI%2FHpiTOuJU5UJGIV2ZcB8I8E7lE0e9YljtAmGlTp9zkfoPwwjQi9BPT8z4s%2FZ8YsZjE81hg8d4qaivffF6tA1r8%2FilVLl6gV8bNEBvnumsBekJxk7iw1f1VDw%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/m21379as/wandb-metadata.json?Expires=1689061048&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=EFp%2F4XeatmQPDNuViZEytbb7tXeVXXc%2FjOoGPWh0s0RHsw2lcHrwYYnOr8e2iSqAgph248bTgvyHvPj9NG5wtqzPcE8%2F2e5lFLvRL3J1fZ3AqvOfzDDasdl7Tpv8hHaJo3lWicNR1Xxc37ROd%2FcpRMkImhLMMGYNkHaWvGXYTmlLTfYEe2GXG2ugkdd0uEw7xk1Qu33kTaxE2cCH0u7DL8oc%2BeC3mI%2FHpiTOuJU5UJGIV2ZcB8I8E7lE0e9YljtAmGlTp9zkfoPwwjQi9BPT8z4s%2FZ8YsZjE81hg8d4qaivffF6tA1r8%2FilVLl6gV8bNEBvnumsBekJxk7iw1f1VDw%3D%3D
2023-07-10 15:37:28,865 ERROR   wandb-upload_0:45354 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3609'}
2023-07-10 15:37:28,865 ERROR   wandb-upload_0:45354 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/m21379as/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 15:37:28,967 DEBUG   SenderThread:45354 [sender.py:send():369] send: telemetry
2023-07-10 15:37:29,288 INFO    Thread-17 :45354 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_153726-m21379as/files/output.log
2023-07-10 15:37:29,288 INFO    Thread-17 :45354 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_153726-m21379as/files/wandb-metadata.json
2023-07-10 15:37:30,874 ERROR   wandb-upload_0:45354 [upload_job.py:push():136] Failed to upload file: /tmp/tmp8y4s_85lwandb/rb999in3-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/m21379as/wandb-metadata.json?Expires=1689061048&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=EFp%2F4XeatmQPDNuViZEytbb7tXeVXXc%2FjOoGPWh0s0RHsw2lcHrwYYnOr8e2iSqAgph248bTgvyHvPj9NG5wtqzPcE8%2F2e5lFLvRL3J1fZ3AqvOfzDDasdl7Tpv8hHaJo3lWicNR1Xxc37ROd%2FcpRMkImhLMMGYNkHaWvGXYTmlLTfYEe2GXG2ugkdd0uEw7xk1Qu33kTaxE2cCH0u7DL8oc%2BeC3mI%2FHpiTOuJU5UJGIV2ZcB8I8E7lE0e9YljtAmGlTp9zkfoPwwjQi9BPT8z4s%2FZ8YsZjE81hg8d4qaivffF6tA1r8%2FilVLl6gV8bNEBvnumsBekJxk7iw1f1VDw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 15:37:31,289 INFO    Thread-17 :45354 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_153726-m21379as/files/output.log
2023-07-10 15:37:31,399 ERROR   Thread-16 :45354 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmp8y4s_85lwandb/rb999in3-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/m21379as/wandb-metadata.json?Expires=1689061048&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=EFp%2F4XeatmQPDNuViZEytbb7tXeVXXc%2FjOoGPWh0s0RHsw2lcHrwYYnOr8e2iSqAgph248bTgvyHvPj9NG5wtqzPcE8%2F2e5lFLvRL3J1fZ3AqvOfzDDasdl7Tpv8hHaJo3lWicNR1Xxc37ROd%2FcpRMkImhLMMGYNkHaWvGXYTmlLTfYEe2GXG2ugkdd0uEw7xk1Qu33kTaxE2cCH0u7DL8oc%2BeC3mI%2FHpiTOuJU5UJGIV2ZcB8I8E7lE0e9YljtAmGlTp9zkfoPwwjQi9BPT8z4s%2FZ8YsZjE81hg8d4qaivffF6tA1r8%2FilVLl6gV8bNEBvnumsBekJxk7iw1f1VDw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 15:37:31,979 DEBUG   HandlerThread:45354 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:37:33,290 INFO    Thread-17 :45354 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_153726-m21379as/files/output.log
2023-07-10 15:37:37,296 DEBUG   HandlerThread:45354 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:37:41,292 INFO    Thread-17 :45354 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_153726-m21379as/files/output.log
2023-07-10 15:37:42,349 DEBUG   HandlerThread:45354 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:37:43,381 DEBUG   HandlerThread:45354 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 15:37:43,381 DEBUG   SenderThread:45354 [sender.py:send_request():396] send_request: stop_status
