2023-07-10 21:02:50,944 INFO    StreamThr :40728 [internal.py:wandb_internal():86] W&B internal server running at pid: 40728, started at: 2023-07-10 21:02:50.943758
2023-07-10 21:02:50,946 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status
2023-07-10 21:02:50,949 INFO    WriterThread:40728 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210250-t2lb37bm/run-t2lb37bm.wandb
2023-07-10 21:02:50,951 DEBUG   SenderThread:40728 [sender.py:send():369] send: header
2023-07-10 21:02:50,951 DEBUG   SenderThread:40728 [sender.py:send():369] send: run
2023-07-10 21:02:51,895 INFO    SenderThread:40728 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210250-t2lb37bm/files
2023-07-10 21:02:51,895 INFO    SenderThread:40728 [sender.py:_start_run_threads():1100] run started: t2lb37bm with start time 1688994170.943505
2023-07-10 21:02:51,895 DEBUG   SenderThread:40728 [sender.py:send_request():396] send_request: summary_record
2023-07-10 21:02:51,895 INFO    SenderThread:40728 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 21:02:51,900 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 21:02:51,900 DEBUG   SenderThread:40728 [sender.py:send_request():396] send_request: check_version
2023-07-10 21:02:52,104 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 21:02:52,118 DEBUG   HandlerThread:40728 [system_info.py:__init__():31] System info init
2023-07-10 21:02:52,118 DEBUG   HandlerThread:40728 [system_info.py:__init__():46] System info init done
2023-07-10 21:02:52,118 INFO    HandlerThread:40728 [system_monitor.py:start():181] Starting system monitor
2023-07-10 21:02:52,120 INFO    HandlerThread:40728 [system_monitor.py:probe():201] Collecting system info
2023-07-10 21:02:52,121 INFO    SystemMonitor:40728 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 21:02:52,128 INFO    SystemMonitor:40728 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 21:02:52,132 INFO    SystemMonitor:40728 [interfaces.py:start():190] Started disk monitoring
2023-07-10 21:02:52,133 INFO    SystemMonitor:40728 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 21:02:52,134 INFO    SystemMonitor:40728 [interfaces.py:start():190] Started memory monitoring
2023-07-10 21:02:52,134 INFO    SystemMonitor:40728 [interfaces.py:start():190] Started network monitoring
2023-07-10 21:02:52,149 DEBUG   HandlerThread:40728 [system_info.py:probe():195] Probing system
2023-07-10 21:02:52,153 DEBUG   HandlerThread:40728 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 21:02:52,153 DEBUG   HandlerThread:40728 [system_info.py:probe():240] Probing system done
2023-07-10 21:02:52,153 DEBUG   HandlerThread:40728 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T13:02:52.149440', 'startedAt': '2023-07-10T13:02:50.934819', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 2520.4628749999997, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 2266.36, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1531.81, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1493.475, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 4190.303, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2178.412, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.018550872802734375}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-10 21:02:52,153 INFO    HandlerThread:40728 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 21:02:52,153 INFO    HandlerThread:40728 [system_monitor.py:probe():214] Publishing system info
2023-07-10 21:02:52,153 DEBUG   HandlerThread:40728 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 21:02:52,154 DEBUG   HandlerThread:40728 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 21:02:52,154 DEBUG   HandlerThread:40728 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 21:02:52,897 INFO    Thread-17 :40728 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210250-t2lb37bm/files/conda-environment.yaml
2023-07-10 21:02:52,898 INFO    Thread-17 :40728 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210250-t2lb37bm/files/wandb-summary.json
2023-07-10 21:02:52,898 INFO    Thread-17 :40728 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210250-t2lb37bm/files/requirements.txt
2023-07-10 21:02:53,031 DEBUG   HandlerThread:40728 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 21:02:53,032 INFO    HandlerThread:40728 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 21:02:53,035 DEBUG   SenderThread:40728 [sender.py:send():369] send: files
2023-07-10 21:02:53,035 INFO    SenderThread:40728 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 21:02:53,042 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:02:53,043 DEBUG   SenderThread:40728 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:02:53,508 ERROR   wandb-upload_0:40728 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/t2lb37bm/wandb-metadata.json?Expires=1689080573&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jea8iqOFAVxzftfhSOlLCBV%2FdC0gPmoUCcKlKmjRp%2FpuwRXLpPIs3NEE1XCvNrvlVdn3y8ZSdduJL9cg0fQ8JRQt5XY3FYJfWQoMu1wk%2FNo5CDVGn420R1O9a%2FhUNnUikYPAA8y9P%2F2%2BBbB8FSIDHAuJwqupzSF2wiXlWRX8RGRJcYs6D2iUzRIPtWcDR1ru06ULaS%2Bz6iRPaHtSERn4shPkP7Kcw%2F14T44A5QXV1jP7BSte%2Blqks4eufbXhfQ3Yna6IM1S0R%2B203lEsksIhGn3fwvqixv6jhdAjdEabpbfYpGl0oKn98FIh7WUAxHslm%2BvhDroVizWsJsd8%2Bek%2Fug%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/t2lb37bm/wandb-metadata.json?Expires=1689080573&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jea8iqOFAVxzftfhSOlLCBV%2FdC0gPmoUCcKlKmjRp%2FpuwRXLpPIs3NEE1XCvNrvlVdn3y8ZSdduJL9cg0fQ8JRQt5XY3FYJfWQoMu1wk%2FNo5CDVGn420R1O9a%2FhUNnUikYPAA8y9P%2F2%2BBbB8FSIDHAuJwqupzSF2wiXlWRX8RGRJcYs6D2iUzRIPtWcDR1ru06ULaS%2Bz6iRPaHtSERn4shPkP7Kcw%2F14T44A5QXV1jP7BSte%2Blqks4eufbXhfQ3Yna6IM1S0R%2B203lEsksIhGn3fwvqixv6jhdAjdEabpbfYpGl0oKn98FIh7WUAxHslm%2BvhDroVizWsJsd8%2Bek%2Fug%3D%3D
2023-07-10 21:02:53,508 ERROR   wandb-upload_0:40728 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3614'}
2023-07-10 21:02:53,508 ERROR   wandb-upload_0:40728 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/t2lb37bm/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 21:02:53,612 DEBUG   SenderThread:40728 [sender.py:send():369] send: telemetry
2023-07-10 21:02:53,897 INFO    Thread-17 :40728 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210250-t2lb37bm/files/conda-environment.yaml
2023-07-10 21:02:53,898 INFO    Thread-17 :40728 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210250-t2lb37bm/files/output.log
2023-07-10 21:02:53,898 INFO    Thread-17 :40728 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210250-t2lb37bm/files/wandb-metadata.json
2023-07-10 21:02:55,513 ERROR   wandb-upload_0:40728 [upload_job.py:push():136] Failed to upload file: /tmp/tmp8whnz6znwandb/4wl6g2jq-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/t2lb37bm/wandb-metadata.json?Expires=1689080573&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jea8iqOFAVxzftfhSOlLCBV%2FdC0gPmoUCcKlKmjRp%2FpuwRXLpPIs3NEE1XCvNrvlVdn3y8ZSdduJL9cg0fQ8JRQt5XY3FYJfWQoMu1wk%2FNo5CDVGn420R1O9a%2FhUNnUikYPAA8y9P%2F2%2BBbB8FSIDHAuJwqupzSF2wiXlWRX8RGRJcYs6D2iUzRIPtWcDR1ru06ULaS%2Bz6iRPaHtSERn4shPkP7Kcw%2F14T44A5QXV1jP7BSte%2Blqks4eufbXhfQ3Yna6IM1S0R%2B203lEsksIhGn3fwvqixv6jhdAjdEabpbfYpGl0oKn98FIh7WUAxHslm%2BvhDroVizWsJsd8%2Bek%2Fug%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 21:02:55,896 INFO    Thread-17 :40728 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210250-t2lb37bm/files/output.log
2023-07-10 21:02:55,941 ERROR   Thread-16 :40728 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmp8whnz6znwandb/4wl6g2jq-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/t2lb37bm/wandb-metadata.json?Expires=1689080573&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=jea8iqOFAVxzftfhSOlLCBV%2FdC0gPmoUCcKlKmjRp%2FpuwRXLpPIs3NEE1XCvNrvlVdn3y8ZSdduJL9cg0fQ8JRQt5XY3FYJfWQoMu1wk%2FNo5CDVGn420R1O9a%2FhUNnUikYPAA8y9P%2F2%2BBbB8FSIDHAuJwqupzSF2wiXlWRX8RGRJcYs6D2iUzRIPtWcDR1ru06ULaS%2Bz6iRPaHtSERn4shPkP7Kcw%2F14T44A5QXV1jP7BSte%2Blqks4eufbXhfQ3Yna6IM1S0R%2B203lEsksIhGn3fwvqixv6jhdAjdEabpbfYpGl0oKn98FIh7WUAxHslm%2BvhDroVizWsJsd8%2Bek%2Fug%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 21:02:56,286 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:02:57,897 INFO    Thread-17 :40728 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210250-t2lb37bm/files/output.log
2023-07-10 21:03:01,497 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:03:03,515 DEBUG   SenderThread:40728 [sender.py:send():369] send: telemetry
2023-07-10 21:03:03,899 INFO    Thread-17 :40728 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210250-t2lb37bm/files/output.log
2023-07-10 21:03:05,900 INFO    Thread-17 :40728 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210250-t2lb37bm/files/output.log
2023-07-10 21:03:06,582 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:03:08,040 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:03:08,041 DEBUG   SenderThread:40728 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:03:09,827 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 21:03:09,902 INFO    Thread-17 :40728 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210250-t2lb37bm/files/output.log
2023-07-10 21:03:11,904 INFO    Thread-17 :40728 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210250-t2lb37bm/files/output.log
2023-07-10 21:03:12,032 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:03:17,034 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:03:22,040 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:03:22,914 INFO    Thread-17 :40728 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_210250-t2lb37bm/files/config.yaml
2023-07-10 21:03:23,043 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:03:23,045 DEBUG   SenderThread:40728 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:03:28,287 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:03:33,289 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:03:38,043 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:03:38,045 DEBUG   SenderThread:40728 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:03:39,272 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:03:44,273 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:03:49,275 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:03:52,135 DEBUG   SystemMonitor:40728 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-10 21:03:52,140 DEBUG   SenderThread:40728 [sender.py:send():369] send: stats
2023-07-10 21:03:53,043 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:03:53,044 DEBUG   SenderThread:40728 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:03:54,293 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:03:59,295 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:04:04,297 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:04:08,044 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:04:08,045 DEBUG   SenderThread:40728 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:04:10,273 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:04:15,274 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:04:20,276 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:04:22,143 DEBUG   SenderThread:40728 [sender.py:send():369] send: stats
2023-07-10 21:04:23,044 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:04:23,045 DEBUG   SenderThread:40728 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:04:26,276 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:04:31,278 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:04:36,280 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:04:38,044 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:04:38,045 DEBUG   SenderThread:40728 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:04:42,276 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:04:47,277 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:04:52,148 DEBUG   SenderThread:40728 [sender.py:send():369] send: stats
2023-07-10 21:04:53,044 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:04:53,046 DEBUG   SenderThread:40728 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:04:53,313 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:04:58,314 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:05:03,315 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 21:05:08,045 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 21:05:08,046 DEBUG   SenderThread:40728 [sender.py:send_request():396] send_request: stop_status
2023-07-10 21:05:09,303 DEBUG   HandlerThread:40728 [handler.py:handle_request():144] handle_request: status_report
