2023-07-11 14:01:50,179 INFO    StreamThr :110282 [internal.py:wandb_internal():86] W&B internal server running at pid: 110282, started at: 2023-07-11 14:01:50.179137
2023-07-11 14:01:50,182 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status
2023-07-11 14:01:50,184 INFO    WriterThread:110282 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_140150-tiyzo7ru/run-tiyzo7ru.wandb
2023-07-11 14:01:50,185 DEBUG   SenderThread:110282 [sender.py:send():369] send: header
2023-07-11 14:01:50,186 DEBUG   SenderThread:110282 [sender.py:send():369] send: run
2023-07-11 14:01:51,115 INFO    SenderThread:110282 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_140150-tiyzo7ru/files
2023-07-11 14:01:51,115 INFO    SenderThread:110282 [sender.py:_start_run_threads():1100] run started: tiyzo7ru with start time 1689055310.178295
2023-07-11 14:01:51,115 DEBUG   SenderThread:110282 [sender.py:send_request():396] send_request: summary_record
2023-07-11 14:01:51,115 INFO    SenderThread:110282 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-11 14:01:51,120 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: check_version
2023-07-11 14:01:51,120 DEBUG   SenderThread:110282 [sender.py:send_request():396] send_request: check_version
2023-07-11 14:01:51,301 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: run_start
2023-07-11 14:01:51,306 DEBUG   HandlerThread:110282 [system_info.py:__init__():31] System info init
2023-07-11 14:01:51,306 DEBUG   HandlerThread:110282 [system_info.py:__init__():46] System info init done
2023-07-11 14:01:51,306 INFO    HandlerThread:110282 [system_monitor.py:start():181] Starting system monitor
2023-07-11 14:01:51,307 INFO    HandlerThread:110282 [system_monitor.py:probe():201] Collecting system info
2023-07-11 14:01:51,307 INFO    SystemMonitor:110282 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-11 14:01:51,309 INFO    SystemMonitor:110282 [interfaces.py:start():190] Started cpu monitoring
2023-07-11 14:01:51,310 INFO    SystemMonitor:110282 [interfaces.py:start():190] Started disk monitoring
2023-07-11 14:01:51,311 INFO    SystemMonitor:110282 [interfaces.py:start():190] Started gpu monitoring
2023-07-11 14:01:51,312 INFO    SystemMonitor:110282 [interfaces.py:start():190] Started memory monitoring
2023-07-11 14:01:51,313 INFO    SystemMonitor:110282 [interfaces.py:start():190] Started network monitoring
2023-07-11 14:01:51,328 DEBUG   HandlerThread:110282 [system_info.py:probe():195] Probing system
2023-07-11 14:01:51,332 DEBUG   HandlerThread:110282 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-11 14:01:51,332 DEBUG   HandlerThread:110282 [system_info.py:probe():240] Probing system done
2023-07-11 14:01:51,332 DEBUG   HandlerThread:110282 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-11T06:01:51.328175', 'startedAt': '2023-07-11T06:01:50.170330', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3858.9149166666666, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.067, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.039, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5099.938, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5099.953, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 3699.901, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 3714.06, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.0199737548828125}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-11 14:01:51,332 INFO    HandlerThread:110282 [system_monitor.py:probe():211] Finished collecting system info
2023-07-11 14:01:51,332 INFO    HandlerThread:110282 [system_monitor.py:probe():214] Publishing system info
2023-07-11 14:01:51,332 DEBUG   HandlerThread:110282 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-11 14:01:51,332 DEBUG   HandlerThread:110282 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-11 14:01:51,332 DEBUG   HandlerThread:110282 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-11 14:01:52,118 INFO    Thread-17 :110282 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_140150-tiyzo7ru/files/wandb-summary.json
2023-07-11 14:01:52,118 INFO    Thread-17 :110282 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_140150-tiyzo7ru/files/conda-environment.yaml
2023-07-11 14:01:52,118 INFO    Thread-17 :110282 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_140150-tiyzo7ru/files/requirements.txt
2023-07-11 14:01:52,157 DEBUG   HandlerThread:110282 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-11 14:01:52,158 INFO    HandlerThread:110282 [system_monitor.py:probe():216] Finished publishing system info
2023-07-11 14:01:52,161 DEBUG   SenderThread:110282 [sender.py:send():369] send: files
2023-07-11 14:01:52,161 INFO    SenderThread:110282 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-11 14:01:52,167 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 14:01:52,168 DEBUG   SenderThread:110282 [sender.py:send_request():396] send_request: stop_status
2023-07-11 14:01:52,636 ERROR   wandb-upload_0:110282 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/tiyzo7ru/wandb-metadata.json?Expires=1689141712&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Cuj1pBreXgKGxWo2LN21VC%2BNjCtopr8DjhqAWjoGK87lrICEjhE7UmpnyE0e3iPoE1GP0qv2yYcf4tdbYDb%2BJrjT6kKWqrKRKzTbA2qxcQv8lmPW8iP2GXQObp2PcjKQBSj5OA7Kx9J09q7r5qb6eGM2mLYCog2%2B1Qwonu981AlDgix%2Fwd866oZ4GdeV%2BU4CrRPlK6478eUEEm7KLrv0HuF3d5W9zQsNRvXtR0qZG3pOSMYRo%2FzDkDBjL00ll5JETCECKYgJC3a8lG5P%2F9kRO%2F8wg2BnAA7duYUiJ8c3vp3%2FrTfAG3hdxYz74o%2FAq8qYyAI8EEp305nDm9%2B2tnD1LA%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/tiyzo7ru/wandb-metadata.json?Expires=1689141712&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Cuj1pBreXgKGxWo2LN21VC%2BNjCtopr8DjhqAWjoGK87lrICEjhE7UmpnyE0e3iPoE1GP0qv2yYcf4tdbYDb%2BJrjT6kKWqrKRKzTbA2qxcQv8lmPW8iP2GXQObp2PcjKQBSj5OA7Kx9J09q7r5qb6eGM2mLYCog2%2B1Qwonu981AlDgix%2Fwd866oZ4GdeV%2BU4CrRPlK6478eUEEm7KLrv0HuF3d5W9zQsNRvXtR0qZG3pOSMYRo%2FzDkDBjL00ll5JETCECKYgJC3a8lG5P%2F9kRO%2F8wg2BnAA7duYUiJ8c3vp3%2FrTfAG3hdxYz74o%2FAq8qYyAI8EEp305nDm9%2B2tnD1LA%3D%3D
2023-07-11 14:01:52,636 ERROR   wandb-upload_0:110282 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3615'}
2023-07-11 14:01:52,636 ERROR   wandb-upload_0:110282 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/tiyzo7ru/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-11 14:01:52,738 DEBUG   SenderThread:110282 [sender.py:send():369] send: telemetry
2023-07-11 14:01:53,119 INFO    Thread-17 :110282 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_140150-tiyzo7ru/files/output.log
2023-07-11 14:01:53,119 INFO    Thread-17 :110282 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_140150-tiyzo7ru/files/wandb-metadata.json
2023-07-11 14:01:54,642 ERROR   wandb-upload_0:110282 [upload_job.py:push():136] Failed to upload file: /tmp/tmpbnwmlyb7wandb/v9f7rbhp-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/tiyzo7ru/wandb-metadata.json?Expires=1689141712&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Cuj1pBreXgKGxWo2LN21VC%2BNjCtopr8DjhqAWjoGK87lrICEjhE7UmpnyE0e3iPoE1GP0qv2yYcf4tdbYDb%2BJrjT6kKWqrKRKzTbA2qxcQv8lmPW8iP2GXQObp2PcjKQBSj5OA7Kx9J09q7r5qb6eGM2mLYCog2%2B1Qwonu981AlDgix%2Fwd866oZ4GdeV%2BU4CrRPlK6478eUEEm7KLrv0HuF3d5W9zQsNRvXtR0qZG3pOSMYRo%2FzDkDBjL00ll5JETCECKYgJC3a8lG5P%2F9kRO%2F8wg2BnAA7duYUiJ8c3vp3%2FrTfAG3hdxYz74o%2FAq8qYyAI8EEp305nDm9%2B2tnD1LA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 14:01:55,120 INFO    Thread-17 :110282 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_140150-tiyzo7ru/files/output.log
2023-07-11 14:01:55,307 ERROR   Thread-16 :110282 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpbnwmlyb7wandb/v9f7rbhp-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/tiyzo7ru/wandb-metadata.json?Expires=1689141712&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Cuj1pBreXgKGxWo2LN21VC%2BNjCtopr8DjhqAWjoGK87lrICEjhE7UmpnyE0e3iPoE1GP0qv2yYcf4tdbYDb%2BJrjT6kKWqrKRKzTbA2qxcQv8lmPW8iP2GXQObp2PcjKQBSj5OA7Kx9J09q7r5qb6eGM2mLYCog2%2B1Qwonu981AlDgix%2Fwd866oZ4GdeV%2BU4CrRPlK6478eUEEm7KLrv0HuF3d5W9zQsNRvXtR0qZG3pOSMYRo%2FzDkDBjL00ll5JETCECKYgJC3a8lG5P%2F9kRO%2F8wg2BnAA7duYUiJ8c3vp3%2FrTfAG3hdxYz74o%2FAq8qYyAI8EEp305nDm9%2B2tnD1LA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 14:01:55,398 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:01:57,120 INFO    Thread-17 :110282 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_140150-tiyzo7ru/files/output.log
2023-07-11 14:02:00,600 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:02:04,215 DEBUG   SenderThread:110282 [sender.py:send():369] send: telemetry
2023-07-11 14:02:05,123 INFO    Thread-17 :110282 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_140150-tiyzo7ru/files/output.log
2023-07-11 14:02:06,294 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:02:07,124 INFO    Thread-17 :110282 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_140150-tiyzo7ru/files/output.log
2023-07-11 14:02:07,166 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 14:02:07,166 DEBUG   SenderThread:110282 [sender.py:send_request():396] send_request: stop_status
2023-07-11 14:02:11,125 INFO    Thread-17 :110282 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_140150-tiyzo7ru/files/output.log
2023-07-11 14:02:11,829 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:02:13,126 INFO    Thread-17 :110282 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_140150-tiyzo7ru/files/output.log
2023-07-11 14:02:17,098 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:02:22,104 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:02:22,166 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 14:02:22,361 DEBUG   SenderThread:110282 [sender.py:send_request():396] send_request: stop_status
2023-07-11 14:02:23,129 INFO    Thread-17 :110282 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_140150-tiyzo7ru/files/config.yaml
2023-07-11 14:02:27,597 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:02:32,597 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:02:37,166 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 14:02:37,167 DEBUG   SenderThread:110282 [sender.py:send_request():396] send_request: stop_status
2023-07-11 14:02:38,404 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:02:43,404 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:02:48,405 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:02:51,313 DEBUG   SystemMonitor:110282 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-11 14:02:51,315 DEBUG   SenderThread:110282 [sender.py:send():369] send: stats
2023-07-11 14:02:52,167 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 14:02:52,167 DEBUG   SenderThread:110282 [sender.py:send_request():396] send_request: stop_status
2023-07-11 14:02:54,389 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:02:59,390 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:03:04,391 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:03:07,167 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 14:03:07,167 DEBUG   SenderThread:110282 [sender.py:send_request():396] send_request: stop_status
2023-07-11 14:03:09,396 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:03:14,397 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:03:19,398 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:03:21,316 DEBUG   SenderThread:110282 [sender.py:send():369] send: stats
2023-07-11 14:03:22,167 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 14:03:22,168 DEBUG   SenderThread:110282 [sender.py:send_request():396] send_request: stop_status
2023-07-11 14:03:24,399 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 14:03:29,399 DEBUG   HandlerThread:110282 [handler.py:handle_request():144] handle_request: status_report
