2023-07-10 19:02:14,389 INFO    StreamThr :25127 [internal.py:wandb_internal():86] W&B internal server running at pid: 25127, started at: 2023-07-10 19:02:14.389024
2023-07-10 19:02:14,392 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status
2023-07-10 19:02:14,394 INFO    WriterThread:25127 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/run-dmls1ziy.wandb
2023-07-10 19:02:14,394 DEBUG   SenderThread:25127 [sender.py:send():369] send: header
2023-07-10 19:02:14,394 DEBUG   SenderThread:25127 [sender.py:send():369] send: run
2023-07-10 19:02:15,255 INFO    SenderThread:25127 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files
2023-07-10 19:02:15,255 INFO    SenderThread:25127 [sender.py:_start_run_threads():1100] run started: dmls1ziy with start time 1688986934.389731
2023-07-10 19:02:15,256 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:02:15,256 INFO    SenderThread:25127 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:02:15,262 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 19:02:15,262 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: check_version
2023-07-10 19:02:15,443 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 19:02:15,448 DEBUG   HandlerThread:25127 [system_info.py:__init__():31] System info init
2023-07-10 19:02:15,448 DEBUG   HandlerThread:25127 [system_info.py:__init__():46] System info init done
2023-07-10 19:02:15,448 INFO    HandlerThread:25127 [system_monitor.py:start():181] Starting system monitor
2023-07-10 19:02:15,448 INFO    HandlerThread:25127 [system_monitor.py:probe():201] Collecting system info
2023-07-10 19:02:15,449 INFO    SystemMonitor:25127 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 19:02:15,450 INFO    SystemMonitor:25127 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 19:02:15,451 INFO    SystemMonitor:25127 [interfaces.py:start():190] Started disk monitoring
2023-07-10 19:02:15,452 INFO    SystemMonitor:25127 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 19:02:15,452 INFO    SystemMonitor:25127 [interfaces.py:start():190] Started memory monitoring
2023-07-10 19:02:15,453 INFO    SystemMonitor:25127 [interfaces.py:start():190] Started network monitoring
2023-07-10 19:02:15,469 DEBUG   HandlerThread:25127 [system_info.py:probe():195] Probing system
2023-07-10 19:02:15,473 DEBUG   HandlerThread:25127 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 19:02:15,473 DEBUG   HandlerThread:25127 [system_info.py:probe():240] Probing system done
2023-07-10 19:02:15,473 DEBUG   HandlerThread:25127 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T11:02:15.469899', 'startedAt': '2023-07-10T11:02:14.376773', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3908.6805, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 5101.483, 'min': 800.0, 'max': 5100.0}, {'current': 5099.844, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5099.949, 'min': 800.0, 'max': 5100.0}, {'current': 5100.83, 'min': 800.0, 'max': 5100.0}, {'current': 5100.146, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5099.987, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 4968.047, 'min': 800.0, 'max': 5200.0}, {'current': 5025.158, 'min': 800.0, 'max': 5200.0}, {'current': 5100.263, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5111.86, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 3700.765, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.01815032958984375}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-10 19:02:15,473 INFO    HandlerThread:25127 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 19:02:15,473 INFO    HandlerThread:25127 [system_monitor.py:probe():214] Publishing system info
2023-07-10 19:02:15,473 DEBUG   HandlerThread:25127 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 19:02:15,474 DEBUG   HandlerThread:25127 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 19:02:15,474 DEBUG   HandlerThread:25127 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 19:02:16,235 DEBUG   HandlerThread:25127 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 19:02:16,237 INFO    HandlerThread:25127 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 19:02:16,240 DEBUG   SenderThread:25127 [sender.py:send():369] send: files
2023-07-10 19:02:16,240 INFO    SenderThread:25127 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 19:02:16,246 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:02:16,247 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:02:16,257 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/wandb-metadata.json
2023-07-10 19:02:16,258 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/requirements.txt
2023-07-10 19:02:16,258 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/wandb-summary.json
2023-07-10 19:02:16,258 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/conda-environment.yaml
2023-07-10 19:02:16,724 ERROR   wandb-upload_0:25127 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/wandb-metadata.json?Expires=1689073336&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iP5Evcp53RoCGIcYkjgbj4xPkJpzMJm1khkDEO8TNvO%2BrfKShI1QKwjDfCbxyf1jEZGKmJOOX9AGSpiwuh9mQ6iJn2XxrRXDNdWSm8kgCshY%2FH9HNL4g%2FiJU0TfYnUFtOdu1VR7m6%2BFNJWWjPiANl4jFS4M%2BwtTu%2FhBIC9T3DfHKCxskruCVLrock782MZ8NzLaWeRWt0doZxDN352uUxtTqA5fzpbVeNHGJmEYZIbKNDzClrmSMVk8Z6vNPUff6ZsKyczF4wSGT481hxGaMfssiy2WYntfbdFcQaYkzyuJY9pY78p5hSfm8OLE5n1voVCdVMi9QJZ%2FAlX2ULX%2FI%2BQ%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/wandb-metadata.json?Expires=1689073336&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iP5Evcp53RoCGIcYkjgbj4xPkJpzMJm1khkDEO8TNvO%2BrfKShI1QKwjDfCbxyf1jEZGKmJOOX9AGSpiwuh9mQ6iJn2XxrRXDNdWSm8kgCshY%2FH9HNL4g%2FiJU0TfYnUFtOdu1VR7m6%2BFNJWWjPiANl4jFS4M%2BwtTu%2FhBIC9T3DfHKCxskruCVLrock782MZ8NzLaWeRWt0doZxDN352uUxtTqA5fzpbVeNHGJmEYZIbKNDzClrmSMVk8Z6vNPUff6ZsKyczF4wSGT481hxGaMfssiy2WYntfbdFcQaYkzyuJY9pY78p5hSfm8OLE5n1voVCdVMi9QJZ%2FAlX2ULX%2FI%2BQ%3D%3D
2023-07-10 19:02:16,724 ERROR   wandb-upload_0:25127 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3616'}
2023-07-10 19:02:16,724 ERROR   wandb-upload_0:25127 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:02:16,823 DEBUG   SenderThread:25127 [sender.py:send():369] send: telemetry
2023-07-10 19:02:17,256 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:17,290 ERROR   wandb-upload_0:25127 [upload_job.py:push():136] Failed to upload file: /tmp/tmp51drlw2dwandb/xblrrz3u-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/wandb-metadata.json?Expires=1689073336&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iP5Evcp53RoCGIcYkjgbj4xPkJpzMJm1khkDEO8TNvO%2BrfKShI1QKwjDfCbxyf1jEZGKmJOOX9AGSpiwuh9mQ6iJn2XxrRXDNdWSm8kgCshY%2FH9HNL4g%2FiJU0TfYnUFtOdu1VR7m6%2BFNJWWjPiANl4jFS4M%2BwtTu%2FhBIC9T3DfHKCxskruCVLrock782MZ8NzLaWeRWt0doZxDN352uUxtTqA5fzpbVeNHGJmEYZIbKNDzClrmSMVk8Z6vNPUff6ZsKyczF4wSGT481hxGaMfssiy2WYntfbdFcQaYkzyuJY9pY78p5hSfm8OLE5n1voVCdVMi9QJZ%2FAlX2ULX%2FI%2BQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:02:17,507 ERROR   Thread-16 :25127 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmp51drlw2dwandb/xblrrz3u-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/wandb-metadata.json?Expires=1689073336&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iP5Evcp53RoCGIcYkjgbj4xPkJpzMJm1khkDEO8TNvO%2BrfKShI1QKwjDfCbxyf1jEZGKmJOOX9AGSpiwuh9mQ6iJn2XxrRXDNdWSm8kgCshY%2FH9HNL4g%2FiJU0TfYnUFtOdu1VR7m6%2BFNJWWjPiANl4jFS4M%2BwtTu%2FhBIC9T3DfHKCxskruCVLrock782MZ8NzLaWeRWt0doZxDN352uUxtTqA5fzpbVeNHGJmEYZIbKNDzClrmSMVk8Z6vNPUff6ZsKyczF4wSGT481hxGaMfssiy2WYntfbdFcQaYkzyuJY9pY78p5hSfm8OLE5n1voVCdVMi9QJZ%2FAlX2ULX%2FI%2BQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:02:19,257 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:19,436 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:02:21,257 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:24,620 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:02:26,581 DEBUG   SenderThread:25127 [sender.py:send():369] send: telemetry
2023-07-10 19:02:27,259 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:29,260 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:29,651 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:02:31,244 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:02:31,245 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:02:33,261 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:34,948 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:02:35,262 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:37,263 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:39,263 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:40,323 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:02:41,264 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:43,265 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:45,265 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:45,604 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:02:46,244 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:02:46,245 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:02:46,266 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/config.yaml
2023-07-10 19:02:47,266 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:49,267 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:51,268 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:51,494 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:02:53,268 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:55,269 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:56,755 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:02:57,270 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:02:59,270 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:01,245 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:03:01,245 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:03:01,271 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:02,032 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:03:03,271 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:05,272 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:07,273 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:07,573 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:03:09,274 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:11,274 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:13,221 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:03:13,275 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:15,276 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:15,453 DEBUG   SystemMonitor:25127 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-10 19:03:15,455 DEBUG   SenderThread:25127 [sender.py:send():369] send: stats
2023-07-10 19:03:16,245 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:03:16,245 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:03:17,276 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:18,244 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:03:19,277 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:21,278 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:23,279 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:23,675 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:03:25,279 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:27,280 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:28,837 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:03:29,281 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:31,250 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:03:31,250 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:03:31,281 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:33,282 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:33,973 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:03:35,282 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:37,287 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:39,288 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:39,357 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:03:41,288 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:43,289 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:44,475 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:03:45,290 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:45,456 DEBUG   SenderThread:25127 [sender.py:send():369] send: stats
2023-07-10 19:03:46,250 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:03:46,251 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:03:47,291 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:49,291 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:49,485 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:03:51,292 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:53,292 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:55,264 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:03:55,293 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:57,294 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:03:59,297 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:00,806 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:04:01,250 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:04:01,251 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:04:01,298 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:03,298 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:05,299 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:05,980 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:04:07,300 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:09,300 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:11,166 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:04:11,304 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:14,305 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:15,457 DEBUG   SenderThread:25127 [sender.py:send():369] send: stats
2023-07-10 19:04:16,247 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:04:16,250 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:04:16,250 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:04:16,306 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:18,306 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:20,307 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:21,422 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:04:22,308 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:24,312 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:26,313 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:26,752 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:04:28,314 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:30,315 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:31,250 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:04:31,251 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:04:32,190 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:04:32,316 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:34,316 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:36,317 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:37,460 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:04:38,318 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:40,318 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:41,977 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: partial_history
2023-07-10 19:04:41,978 DEBUG   SenderThread:25127 [sender.py:send():369] send: history
2023-07-10 19:04:41,978 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: summary_record
2023-07-10 19:04:41,978 INFO    SenderThread:25127 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:04:42,319 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:42,319 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/wandb-summary.json
2023-07-10 19:04:42,930 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:04:43,319 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:44,320 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:45,458 DEBUG   SenderThread:25127 [sender.py:send():369] send: stats
2023-07-10 19:04:46,250 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:04:46,251 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:04:46,320 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:48,321 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:48,452 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:04:50,322 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:52,323 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:54,031 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:04:54,323 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:56,324 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:58,325 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:04:59,195 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:05:00,326 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:01,251 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:05:01,251 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:05:02,327 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:04,327 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:04,517 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:05:06,328 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:08,329 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:09,864 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:05:10,330 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:12,330 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:14,331 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:15,213 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:05:15,460 DEBUG   SenderThread:25127 [sender.py:send():369] send: stats
2023-07-10 19:05:16,251 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:05:16,251 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:05:16,331 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:18,332 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:20,333 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:20,452 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:05:22,333 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:24,334 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:25,867 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:05:26,335 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:28,335 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:30,336 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:31,248 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:05:31,251 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:05:31,251 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:05:32,336 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:34,337 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:36,338 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:36,567 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:05:38,338 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:40,339 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:42,076 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:05:42,340 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:44,340 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:45,461 DEBUG   SenderThread:25127 [sender.py:send():369] send: stats
2023-07-10 19:05:46,251 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:05:46,251 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:05:46,341 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:47,096 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:05:48,341 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:50,342 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:52,343 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:52,547 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:05:54,343 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:56,346 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:05:58,012 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:05:58,347 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:06:00,347 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:06:01,254 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 19:06:01,254 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: stop_status
2023-07-10 19:06:02,348 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:06:03,251 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:06:04,349 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:06:06,349 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:06:08,350 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:06:08,681 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:06:10,351 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:06:12,352 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:06:12,978 DEBUG   SenderThread:25127 [sender.py:send():369] send: exit
2023-07-10 19:06:12,978 INFO    SenderThread:25127 [sender.py:send_exit():574] handling exit code: 255
2023-07-10 19:06:12,979 INFO    SenderThread:25127 [sender.py:send_exit():576] handling runtime: 237
2023-07-10 19:06:12,979 INFO    SenderThread:25127 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:06:12,979 INFO    SenderThread:25127 [sender.py:send_exit():582] send defer
2023-07-10 19:06:12,980 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:06:12,980 INFO    HandlerThread:25127 [handler.py:handle_request_defer():170] handle defer: 0
2023-07-10 19:06:12,980 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: defer
2023-07-10 19:06:12,980 INFO    SenderThread:25127 [sender.py:send_request_defer():598] handle sender defer: 0
2023-07-10 19:06:12,980 INFO    SenderThread:25127 [sender.py:transition_state():602] send defer: 1
2023-07-10 19:06:12,980 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:06:12,981 INFO    HandlerThread:25127 [handler.py:handle_request_defer():170] handle defer: 1
2023-07-10 19:06:12,981 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: defer
2023-07-10 19:06:12,981 INFO    SenderThread:25127 [sender.py:send_request_defer():598] handle sender defer: 1
2023-07-10 19:06:12,981 INFO    SenderThread:25127 [sender.py:transition_state():602] send defer: 2
2023-07-10 19:06:12,981 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:06:12,981 INFO    HandlerThread:25127 [handler.py:handle_request_defer():170] handle defer: 2
2023-07-10 19:06:12,981 INFO    HandlerThread:25127 [system_monitor.py:finish():190] Stopping system monitor
2023-07-10 19:06:12,982 DEBUG   SystemMonitor:25127 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-07-10 19:06:12,982 DEBUG   SystemMonitor:25127 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-07-10 19:06:12,983 INFO    HandlerThread:25127 [interfaces.py:finish():202] Joined cpu monitor
2023-07-10 19:06:12,984 INFO    HandlerThread:25127 [interfaces.py:finish():202] Joined disk monitor
2023-07-10 19:06:13,041 INFO    HandlerThread:25127 [interfaces.py:finish():202] Joined gpu monitor
2023-07-10 19:06:13,042 INFO    HandlerThread:25127 [interfaces.py:finish():202] Joined memory monitor
2023-07-10 19:06:13,042 INFO    HandlerThread:25127 [interfaces.py:finish():202] Joined network monitor
2023-07-10 19:06:13,042 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: defer
2023-07-10 19:06:13,042 INFO    SenderThread:25127 [sender.py:send_request_defer():598] handle sender defer: 2
2023-07-10 19:06:13,042 INFO    SenderThread:25127 [sender.py:transition_state():602] send defer: 3
2023-07-10 19:06:13,043 DEBUG   SenderThread:25127 [sender.py:send():369] send: stats
2023-07-10 19:06:13,043 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:06:13,043 INFO    HandlerThread:25127 [handler.py:handle_request_defer():170] handle defer: 3
2023-07-10 19:06:13,043 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: defer
2023-07-10 19:06:13,043 INFO    SenderThread:25127 [sender.py:send_request_defer():598] handle sender defer: 3
2023-07-10 19:06:13,043 INFO    SenderThread:25127 [sender.py:transition_state():602] send defer: 4
2023-07-10 19:06:13,043 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:06:13,043 INFO    HandlerThread:25127 [handler.py:handle_request_defer():170] handle defer: 4
2023-07-10 19:06:13,044 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: defer
2023-07-10 19:06:13,044 INFO    SenderThread:25127 [sender.py:send_request_defer():598] handle sender defer: 4
2023-07-10 19:06:13,044 INFO    SenderThread:25127 [sender.py:transition_state():602] send defer: 5
2023-07-10 19:06:13,044 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:06:13,044 INFO    HandlerThread:25127 [handler.py:handle_request_defer():170] handle defer: 5
2023-07-10 19:06:13,044 DEBUG   SenderThread:25127 [sender.py:send():369] send: summary
2023-07-10 19:06:13,044 INFO    SenderThread:25127 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 19:06:13,045 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: defer
2023-07-10 19:06:13,045 INFO    SenderThread:25127 [sender.py:send_request_defer():598] handle sender defer: 5
2023-07-10 19:06:13,045 INFO    SenderThread:25127 [sender.py:transition_state():602] send defer: 6
2023-07-10 19:06:13,045 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:06:13,045 INFO    HandlerThread:25127 [handler.py:handle_request_defer():170] handle defer: 6
2023-07-10 19:06:13,045 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: defer
2023-07-10 19:06:13,045 INFO    SenderThread:25127 [sender.py:send_request_defer():598] handle sender defer: 6
2023-07-10 19:06:13,046 INFO    SenderThread:25127 [sender.py:transition_state():602] send defer: 7
2023-07-10 19:06:13,046 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 19:06:13,046 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:06:13,046 INFO    HandlerThread:25127 [handler.py:handle_request_defer():170] handle defer: 7
2023-07-10 19:06:13,046 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: defer
2023-07-10 19:06:13,046 INFO    SenderThread:25127 [sender.py:send_request_defer():598] handle sender defer: 7
2023-07-10 19:06:13,352 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/wandb-summary.json
2023-07-10 19:06:13,740 INFO    SenderThread:25127 [sender.py:transition_state():602] send defer: 8
2023-07-10 19:06:13,741 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:06:13,742 INFO    HandlerThread:25127 [handler.py:handle_request_defer():170] handle defer: 8
2023-07-10 19:06:13,742 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: defer
2023-07-10 19:06:13,742 INFO    SenderThread:25127 [sender.py:send_request_defer():598] handle sender defer: 8
2023-07-10 19:06:13,742 INFO    SenderThread:25127 [job_builder.py:build():232] Attempting to build job artifact
2023-07-10 19:06:13,743 INFO    SenderThread:25127 [job_builder.py:build():266] no source found
2023-07-10 19:06:13,743 INFO    SenderThread:25127 [sender.py:transition_state():602] send defer: 9
2023-07-10 19:06:13,743 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:06:13,743 INFO    HandlerThread:25127 [handler.py:handle_request_defer():170] handle defer: 9
2023-07-10 19:06:13,743 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: defer
2023-07-10 19:06:13,743 INFO    SenderThread:25127 [sender.py:send_request_defer():598] handle sender defer: 9
2023-07-10 19:06:13,743 INFO    SenderThread:25127 [dir_watcher.py:finish():359] shutting down directory watcher
2023-07-10 19:06:13,979 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: poll_exit
2023-07-10 19:06:14,352 INFO    Thread-17 :25127 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
2023-07-10 19:06:14,353 INFO    SenderThread:25127 [dir_watcher.py:finish():389] scan: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files
2023-07-10 19:06:14,353 INFO    SenderThread:25127 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/wandb-metadata.json wandb-metadata.json
2023-07-10 19:06:14,353 INFO    SenderThread:25127 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/config.yaml config.yaml
2023-07-10 19:06:14,354 INFO    SenderThread:25127 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/requirements.txt requirements.txt
2023-07-10 19:06:14,354 INFO    SenderThread:25127 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/wandb-summary.json wandb-summary.json
2023-07-10 19:06:14,354 INFO    SenderThread:25127 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/conda-environment.yaml conda-environment.yaml
2023-07-10 19:06:14,354 INFO    SenderThread:25127 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log output.log
2023-07-10 19:06:14,354 INFO    SenderThread:25127 [sender.py:transition_state():602] send defer: 10
2023-07-10 19:06:14,354 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: poll_exit
2023-07-10 19:06:14,355 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:06:14,359 INFO    HandlerThread:25127 [handler.py:handle_request_defer():170] handle defer: 10
2023-07-10 19:06:14,364 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: defer
2023-07-10 19:06:14,364 INFO    SenderThread:25127 [sender.py:send_request_defer():598] handle sender defer: 10
2023-07-10 19:06:14,365 INFO    SenderThread:25127 [file_pusher.py:finish():159] shutting down file pusher
2023-07-10 19:06:14,843 ERROR   wandb-upload_0:25127 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/config.yaml?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=STOevekqXbd21SrV1oHV1tJRMv%2BL1IUX2%2BTrXYYOulPosF8LKyL7s7U%2BGtKA1tG20ITNmHNPkiwLE9nAwqU65U3P4A%2BG4xv%2BlBwlC%2F1jdmXgZs8qG9nw6Atx4q4dTW4p9le9nNMcE8of1g7%2BF6i3TrBo3lkF5c%2B3e39WCchKh267X05t6Vpwm0YHIpH7jLccF7uAEznJ5h8HfHB%2BLjKzrUZD%2F0lhPnwTOmSfL5j%2FgQT6U45zmgYV%2FunK%2BEr18U%2FqAQOyWwovITgC5WvTlNFKeYZ5SASgkFo%2BKqgvWlsczq8Lv7n7XyG8xT%2BVuwqzUMLI3IdFcmd8krHkWlefIhIk9Q%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/config.yaml?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=STOevekqXbd21SrV1oHV1tJRMv%2BL1IUX2%2BTrXYYOulPosF8LKyL7s7U%2BGtKA1tG20ITNmHNPkiwLE9nAwqU65U3P4A%2BG4xv%2BlBwlC%2F1jdmXgZs8qG9nw6Atx4q4dTW4p9le9nNMcE8of1g7%2BF6i3TrBo3lkF5c%2B3e39WCchKh267X05t6Vpwm0YHIpH7jLccF7uAEznJ5h8HfHB%2BLjKzrUZD%2F0lhPnwTOmSfL5j%2FgQT6U45zmgYV%2FunK%2BEr18U%2FqAQOyWwovITgC5WvTlNFKeYZ5SASgkFo%2BKqgvWlsczq8Lv7n7XyG8xT%2BVuwqzUMLI3IdFcmd8krHkWlefIhIk9Q%3D%3D
2023-07-10 19:06:14,844 ERROR   wandb-upload_0:25127 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '526'}
2023-07-10 19:06:14,844 ERROR   wandb-upload_0:25127 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/config.yaml</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:06:14,847 ERROR   wandb-upload_1:25127 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/requirements.txt?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jk6u1hPtW9GQMaZTRUY0UDS4boSy5cDShlePZ%2BKO9MTIhWnlu9ToIMPrIJ9zAqAYkW41PVJOB2wJiXUopr3cGb8tqCHXMilZbdO4AokqjlR0OB0Rhi%2B068%2BYPfvpmfdpxDxK%2BYbVNYoP4ATKhCRM0i7yXXKVloRfoIreMxDyyiHJGSrX5RJRMQoA%2Be6JTWcoLUlnOkjFvCrGAl9F6yWhqb9tVmpAQcZuW4uA2a6F%2BHSRdtE6aPLUYkZ4JbHquKvofooWjhknk8KEA%2FR0IekDsUw7KlqmOE%2FJjg%2Fvj8UkPS%2Fh5pGsgLpNIoNANEa0kTfGGMpB6lCI4lYtifMv3qhvJA%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/requirements.txt?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jk6u1hPtW9GQMaZTRUY0UDS4boSy5cDShlePZ%2BKO9MTIhWnlu9ToIMPrIJ9zAqAYkW41PVJOB2wJiXUopr3cGb8tqCHXMilZbdO4AokqjlR0OB0Rhi%2B068%2BYPfvpmfdpxDxK%2BYbVNYoP4ATKhCRM0i7yXXKVloRfoIreMxDyyiHJGSrX5RJRMQoA%2Be6JTWcoLUlnOkjFvCrGAl9F6yWhqb9tVmpAQcZuW4uA2a6F%2BHSRdtE6aPLUYkZ4JbHquKvofooWjhknk8KEA%2FR0IekDsUw7KlqmOE%2FJjg%2Fvj8UkPS%2Fh5pGsgLpNIoNANEa0kTfGGMpB6lCI4lYtifMv3qhvJA%3D%3D
2023-07-10 19:06:14,847 ERROR   wandb-upload_1:25127 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '926'}
2023-07-10 19:06:14,848 ERROR   wandb-upload_1:25127 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/requirements.txt</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:06:14,980 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: poll_exit
2023-07-10 19:06:14,981 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: poll_exit
2023-07-10 19:06:15,182 ERROR   wandb-upload_2:25127 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/wandb-summary.json?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=U%2BHAzgODaPLTjrlk1%2BVsQHVMpk%2FHp06UVles5Wsyo31YkcPS9kPiOGjOp0ij0jvqB1J3ln7i7HfEOVsSW1EZVsPzdWVoLHbgR0czQDpA1WrXMcptVuhVeNaGUCDEHja5XFGBdjEvEUCHa9u8o9dUpA82XQJ3oPHcQH1vU10bYast5DCTcae1hsA5vlndF8JwgD4UqrtEZ7PCDcq2YM8QQ66%2Bc16LFsE6hNFSielTrIr44DIAeIAorDjloF%2F2OYJOTkKKryR1ATA9l2Uvpx4mmqz7KuYKipGDqwpK0q%2F5O4w5U15HdFr8fW80wwvZZLM42%2BSWGNKIMRSQhmKZDRgPbg%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/wandb-summary.json?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=U%2BHAzgODaPLTjrlk1%2BVsQHVMpk%2FHp06UVles5Wsyo31YkcPS9kPiOGjOp0ij0jvqB1J3ln7i7HfEOVsSW1EZVsPzdWVoLHbgR0czQDpA1WrXMcptVuhVeNaGUCDEHja5XFGBdjEvEUCHa9u8o9dUpA82XQJ3oPHcQH1vU10bYast5DCTcae1hsA5vlndF8JwgD4UqrtEZ7PCDcq2YM8QQ66%2Bc16LFsE6hNFSielTrIr44DIAeIAorDjloF%2F2OYJOTkKKryR1ATA9l2Uvpx4mmqz7KuYKipGDqwpK0q%2F5O4w5U15HdFr8fW80wwvZZLM42%2BSWGNKIMRSQhmKZDRgPbg%3D%3D
2023-07-10 19:06:15,182 ERROR   wandb-upload_2:25127 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '164'}
2023-07-10 19:06:15,182 ERROR   wandb-upload_2:25127 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/wandb-summary.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:06:15,189 ERROR   wandb-upload_3:25127 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/conda-environment.yaml?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=OzMVoFavzQjXseX6mbMr41UZEjiDvXf3303AnXTxg2HVyxF9zjCYPjS3kpGGVayMFBrPA%2BgUHjO8uyy7dNJlu8T%2B5A5jU0ugsjSNxGxhFHRim5%2BavxhOy%2FzCfSbB%2Fe4zvCd1ErvKuWts%2BEBkKVtzq5W5V5%2BDF1L8IJptbpoudNrWU5uxzm7AgDRaMMwgEndWvwVReKLXF10cXg6fm04BpkhuFs7%2FVhjrdIGVXqdBEjDiktjaHCPWl6Uv7kH73f8MCui511zxPPVAeL7WImb9NNCqMG4aifVDpiXIhTAhD5yQzqoCakw%2BCPTWdW1YERL5ExOC6X5%2FekytNuk0Pq%2BSqA%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/conda-environment.yaml?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=OzMVoFavzQjXseX6mbMr41UZEjiDvXf3303AnXTxg2HVyxF9zjCYPjS3kpGGVayMFBrPA%2BgUHjO8uyy7dNJlu8T%2B5A5jU0ugsjSNxGxhFHRim5%2BavxhOy%2FzCfSbB%2Fe4zvCd1ErvKuWts%2BEBkKVtzq5W5V5%2BDF1L8IJptbpoudNrWU5uxzm7AgDRaMMwgEndWvwVReKLXF10cXg6fm04BpkhuFs7%2FVhjrdIGVXqdBEjDiktjaHCPWl6Uv7kH73f8MCui511zxPPVAeL7WImb9NNCqMG4aifVDpiXIhTAhD5yQzqoCakw%2BCPTWdW1YERL5ExOC6X5%2FekytNuk0Pq%2BSqA%3D%3D
2023-07-10 19:06:15,189 ERROR   wandb-upload_3:25127 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1925'}
2023-07-10 19:06:15,190 ERROR   wandb-upload_3:25127 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/conda-environment.yaml</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:06:15,231 ERROR   wandb-upload_4:25127 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/output.log?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hzta34k5Rj3sZJk2yytifCrfNAe%2F8TImHxNVuXr1PIC%2B57yRafPL%2BFTFPRcLKvkaaGmadFVjeyYq6JZ1pAd2MMkzZj8KzDAYuRyEWS%2BlBTiEnIRBGWsNmzD3KDK28gVNppieXck95MQtYk8lLk9rHJWRmoX8WEOKw7QFj3MPWq0q9kvCxGS9jwzDEIPlpYnPfnoqGjZ5oBiSbHUF2AO7kBk63u1kkiHcqI4ByYKJdQPsa8%2FKW9UWKurNRI%2FkLN41SZuMwqFflyiIYIFQQC%2B6pWNeNQfecrvIeFl87Lk1wJz%2Fkz1wj8EwoHqiEWw%2FoTNWju3l14%2FHeR90FpTCLje1IA%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/output.log?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hzta34k5Rj3sZJk2yytifCrfNAe%2F8TImHxNVuXr1PIC%2B57yRafPL%2BFTFPRcLKvkaaGmadFVjeyYq6JZ1pAd2MMkzZj8KzDAYuRyEWS%2BlBTiEnIRBGWsNmzD3KDK28gVNppieXck95MQtYk8lLk9rHJWRmoX8WEOKw7QFj3MPWq0q9kvCxGS9jwzDEIPlpYnPfnoqGjZ5oBiSbHUF2AO7kBk63u1kkiHcqI4ByYKJdQPsa8%2FKW9UWKurNRI%2FkLN41SZuMwqFflyiIYIFQQC%2B6pWNeNQfecrvIeFl87Lk1wJz%2Fkz1wj8EwoHqiEWw%2FoTNWju3l14%2FHeR90FpTCLje1IA%3D%3D
2023-07-10 19:06:15,231 ERROR   wandb-upload_4:25127 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '125393'}
2023-07-10 19:06:15,231 ERROR   wandb-upload_4:25127 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/output.log</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 19:06:15,909 ERROR   wandb-upload_0:25127 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/config.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/config.yaml?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=STOevekqXbd21SrV1oHV1tJRMv%2BL1IUX2%2BTrXYYOulPosF8LKyL7s7U%2BGtKA1tG20ITNmHNPkiwLE9nAwqU65U3P4A%2BG4xv%2BlBwlC%2F1jdmXgZs8qG9nw6Atx4q4dTW4p9le9nNMcE8of1g7%2BF6i3TrBo3lkF5c%2B3e39WCchKh267X05t6Vpwm0YHIpH7jLccF7uAEznJ5h8HfHB%2BLjKzrUZD%2F0lhPnwTOmSfL5j%2FgQT6U45zmgYV%2FunK%2BEr18U%2FqAQOyWwovITgC5WvTlNFKeYZ5SASgkFo%2BKqgvWlsczq8Lv7n7XyG8xT%2BVuwqzUMLI3IdFcmd8krHkWlefIhIk9Q%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:06:15,910 ERROR   wandb-upload_2:25127 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/wandb-summary.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/wandb-summary.json?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=U%2BHAzgODaPLTjrlk1%2BVsQHVMpk%2FHp06UVles5Wsyo31YkcPS9kPiOGjOp0ij0jvqB1J3ln7i7HfEOVsSW1EZVsPzdWVoLHbgR0czQDpA1WrXMcptVuhVeNaGUCDEHja5XFGBdjEvEUCHa9u8o9dUpA82XQJ3oPHcQH1vU10bYast5DCTcae1hsA5vlndF8JwgD4UqrtEZ7PCDcq2YM8QQ66%2Bc16LFsE6hNFSielTrIr44DIAeIAorDjloF%2F2OYJOTkKKryR1ATA9l2Uvpx4mmqz7KuYKipGDqwpK0q%2F5O4w5U15HdFr8fW80wwvZZLM42%2BSWGNKIMRSQhmKZDRgPbg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:06:15,910 ERROR   wandb-upload_1:25127 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/requirements.txt
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/requirements.txt?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jk6u1hPtW9GQMaZTRUY0UDS4boSy5cDShlePZ%2BKO9MTIhWnlu9ToIMPrIJ9zAqAYkW41PVJOB2wJiXUopr3cGb8tqCHXMilZbdO4AokqjlR0OB0Rhi%2B068%2BYPfvpmfdpxDxK%2BYbVNYoP4ATKhCRM0i7yXXKVloRfoIreMxDyyiHJGSrX5RJRMQoA%2Be6JTWcoLUlnOkjFvCrGAl9F6yWhqb9tVmpAQcZuW4uA2a6F%2BHSRdtE6aPLUYkZ4JbHquKvofooWjhknk8KEA%2FR0IekDsUw7KlqmOE%2FJjg%2Fvj8UkPS%2Fh5pGsgLpNIoNANEa0kTfGGMpB6lCI4lYtifMv3qhvJA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:06:15,910 ERROR   wandb-upload_4:25127 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/output.log?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hzta34k5Rj3sZJk2yytifCrfNAe%2F8TImHxNVuXr1PIC%2B57yRafPL%2BFTFPRcLKvkaaGmadFVjeyYq6JZ1pAd2MMkzZj8KzDAYuRyEWS%2BlBTiEnIRBGWsNmzD3KDK28gVNppieXck95MQtYk8lLk9rHJWRmoX8WEOKw7QFj3MPWq0q9kvCxGS9jwzDEIPlpYnPfnoqGjZ5oBiSbHUF2AO7kBk63u1kkiHcqI4ByYKJdQPsa8%2FKW9UWKurNRI%2FkLN41SZuMwqFflyiIYIFQQC%2B6pWNeNQfecrvIeFl87Lk1wJz%2Fkz1wj8EwoHqiEWw%2FoTNWju3l14%2FHeR90FpTCLje1IA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:06:15,911 ERROR   wandb-upload_3:25127 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/conda-environment.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/conda-environment.yaml?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=OzMVoFavzQjXseX6mbMr41UZEjiDvXf3303AnXTxg2HVyxF9zjCYPjS3kpGGVayMFBrPA%2BgUHjO8uyy7dNJlu8T%2B5A5jU0ugsjSNxGxhFHRim5%2BavxhOy%2FzCfSbB%2Fe4zvCd1ErvKuWts%2BEBkKVtzq5W5V5%2BDF1L8IJptbpoudNrWU5uxzm7AgDRaMMwgEndWvwVReKLXF10cXg6fm04BpkhuFs7%2FVhjrdIGVXqdBEjDiktjaHCPWl6Uv7kH73f8MCui511zxPPVAeL7WImb9NNCqMG4aifVDpiXIhTAhD5yQzqoCakw%2BCPTWdW1YERL5ExOC6X5%2FekytNuk0Pq%2BSqA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:06:15,981 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: poll_exit
2023-07-10 19:06:15,982 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: poll_exit
2023-07-10 19:06:16,981 ERROR   Thread-16 :25127 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/config.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/config.yaml?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=STOevekqXbd21SrV1oHV1tJRMv%2BL1IUX2%2BTrXYYOulPosF8LKyL7s7U%2BGtKA1tG20ITNmHNPkiwLE9nAwqU65U3P4A%2BG4xv%2BlBwlC%2F1jdmXgZs8qG9nw6Atx4q4dTW4p9le9nNMcE8of1g7%2BF6i3TrBo3lkF5c%2B3e39WCchKh267X05t6Vpwm0YHIpH7jLccF7uAEznJ5h8HfHB%2BLjKzrUZD%2F0lhPnwTOmSfL5j%2FgQT6U45zmgYV%2FunK%2BEr18U%2FqAQOyWwovITgC5WvTlNFKeYZ5SASgkFo%2BKqgvWlsczq8Lv7n7XyG8xT%2BVuwqzUMLI3IdFcmd8krHkWlefIhIk9Q%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:06:16,983 ERROR   Thread-16 :25127 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/requirements.txt
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/requirements.txt?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jk6u1hPtW9GQMaZTRUY0UDS4boSy5cDShlePZ%2BKO9MTIhWnlu9ToIMPrIJ9zAqAYkW41PVJOB2wJiXUopr3cGb8tqCHXMilZbdO4AokqjlR0OB0Rhi%2B068%2BYPfvpmfdpxDxK%2BYbVNYoP4ATKhCRM0i7yXXKVloRfoIreMxDyyiHJGSrX5RJRMQoA%2Be6JTWcoLUlnOkjFvCrGAl9F6yWhqb9tVmpAQcZuW4uA2a6F%2BHSRdtE6aPLUYkZ4JbHquKvofooWjhknk8KEA%2FR0IekDsUw7KlqmOE%2FJjg%2Fvj8UkPS%2Fh5pGsgLpNIoNANEa0kTfGGMpB6lCI4lYtifMv3qhvJA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:06:16,984 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: poll_exit
2023-07-10 19:06:16,984 ERROR   Thread-16 :25127 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/output.log
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/output.log?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hzta34k5Rj3sZJk2yytifCrfNAe%2F8TImHxNVuXr1PIC%2B57yRafPL%2BFTFPRcLKvkaaGmadFVjeyYq6JZ1pAd2MMkzZj8KzDAYuRyEWS%2BlBTiEnIRBGWsNmzD3KDK28gVNppieXck95MQtYk8lLk9rHJWRmoX8WEOKw7QFj3MPWq0q9kvCxGS9jwzDEIPlpYnPfnoqGjZ5oBiSbHUF2AO7kBk63u1kkiHcqI4ByYKJdQPsa8%2FKW9UWKurNRI%2FkLN41SZuMwqFflyiIYIFQQC%2B6pWNeNQfecrvIeFl87Lk1wJz%2Fkz1wj8EwoHqiEWw%2FoTNWju3l14%2FHeR90FpTCLje1IA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:06:16,985 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: poll_exit
2023-07-10 19:06:16,985 ERROR   Thread-16 :25127 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/conda-environment.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/conda-environment.yaml?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=OzMVoFavzQjXseX6mbMr41UZEjiDvXf3303AnXTxg2HVyxF9zjCYPjS3kpGGVayMFBrPA%2BgUHjO8uyy7dNJlu8T%2B5A5jU0ugsjSNxGxhFHRim5%2BavxhOy%2FzCfSbB%2Fe4zvCd1ErvKuWts%2BEBkKVtzq5W5V5%2BDF1L8IJptbpoudNrWU5uxzm7AgDRaMMwgEndWvwVReKLXF10cXg6fm04BpkhuFs7%2FVhjrdIGVXqdBEjDiktjaHCPWl6Uv7kH73f8MCui511zxPPVAeL7WImb9NNCqMG4aifVDpiXIhTAhD5yQzqoCakw%2BCPTWdW1YERL5ExOC6X5%2FekytNuk0Pq%2BSqA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:06:16,986 ERROR   Thread-16 :25127 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_190214-dmls1ziy/files/wandb-summary.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/dmls1ziy/wandb-summary.json?Expires=1689073574&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=U%2BHAzgODaPLTjrlk1%2BVsQHVMpk%2FHp06UVles5Wsyo31YkcPS9kPiOGjOp0ij0jvqB1J3ln7i7HfEOVsSW1EZVsPzdWVoLHbgR0czQDpA1WrXMcptVuhVeNaGUCDEHja5XFGBdjEvEUCHa9u8o9dUpA82XQJ3oPHcQH1vU10bYast5DCTcae1hsA5vlndF8JwgD4UqrtEZ7PCDcq2YM8QQ66%2Bc16LFsE6hNFSielTrIr44DIAeIAorDjloF%2F2OYJOTkKKryR1ATA9l2Uvpx4mmqz7KuYKipGDqwpK0q%2F5O4w5U15HdFr8fW80wwvZZLM42%2BSWGNKIMRSQhmKZDRgPbg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 19:06:17,186 INFO    Thread-16 :25127 [sender.py:transition_state():602] send defer: 11
2023-07-10 19:06:17,187 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:06:17,187 INFO    HandlerThread:25127 [handler.py:handle_request_defer():170] handle defer: 11
2023-07-10 19:06:17,187 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: defer
2023-07-10 19:06:17,187 INFO    SenderThread:25127 [sender.py:send_request_defer():598] handle sender defer: 11
2023-07-10 19:06:17,187 INFO    SenderThread:25127 [file_pusher.py:join():164] waiting for file pusher
2023-07-10 19:06:17,187 INFO    SenderThread:25127 [sender.py:transition_state():602] send defer: 12
2023-07-10 19:06:17,188 DEBUG   HandlerThread:25127 [handler.py:handle_request():144] handle_request: defer
2023-07-10 19:06:17,188 INFO    HandlerThread:25127 [handler.py:handle_request_defer():170] handle defer: 12
2023-07-10 19:06:17,188 DEBUG   SenderThread:25127 [sender.py:send_request():396] send_request: defer
2023-07-10 19:06:17,188 INFO    SenderThread:25127 [sender.py:send_request_defer():598] handle sender defer: 12
