2023-07-11 12:07:01,503 INFO    StreamThr :105878 [internal.py:wandb_internal():86] W&B internal server running at pid: 105878, started at: 2023-07-11 12:07:01.503523
2023-07-11 12:07:01,507 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status
2023-07-11 12:07:01,509 INFO    WriterThread:105878 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120701-e7ceae04/run-e7ceae04.wandb
2023-07-11 12:07:01,511 DEBUG   SenderThread:105878 [sender.py:send():369] send: header
2023-07-11 12:07:01,511 DEBUG   SenderThread:105878 [sender.py:send():369] send: run
2023-07-11 12:07:02,421 INFO    SenderThread:105878 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120701-e7ceae04/files
2023-07-11 12:07:02,422 INFO    SenderThread:105878 [sender.py:_start_run_threads():1100] run started: e7ceae04 with start time 1689048421.50263
2023-07-11 12:07:02,422 DEBUG   SenderThread:105878 [sender.py:send_request():396] send_request: summary_record
2023-07-11 12:07:02,422 INFO    SenderThread:105878 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-11 12:07:02,430 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: check_version
2023-07-11 12:07:02,430 DEBUG   SenderThread:105878 [sender.py:send_request():396] send_request: check_version
2023-07-11 12:07:02,625 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: run_start
2023-07-11 12:07:02,630 DEBUG   HandlerThread:105878 [system_info.py:__init__():31] System info init
2023-07-11 12:07:02,630 DEBUG   HandlerThread:105878 [system_info.py:__init__():46] System info init done
2023-07-11 12:07:02,630 INFO    HandlerThread:105878 [system_monitor.py:start():181] Starting system monitor
2023-07-11 12:07:02,631 INFO    SystemMonitor:105878 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-11 12:07:02,631 INFO    HandlerThread:105878 [system_monitor.py:probe():201] Collecting system info
2023-07-11 12:07:02,632 INFO    SystemMonitor:105878 [interfaces.py:start():190] Started cpu monitoring
2023-07-11 12:07:02,633 INFO    SystemMonitor:105878 [interfaces.py:start():190] Started disk monitoring
2023-07-11 12:07:02,634 INFO    SystemMonitor:105878 [interfaces.py:start():190] Started gpu monitoring
2023-07-11 12:07:02,635 INFO    SystemMonitor:105878 [interfaces.py:start():190] Started memory monitoring
2023-07-11 12:07:02,636 INFO    SystemMonitor:105878 [interfaces.py:start():190] Started network monitoring
2023-07-11 12:07:02,651 DEBUG   HandlerThread:105878 [system_info.py:probe():195] Probing system
2023-07-11 12:07:02,655 DEBUG   HandlerThread:105878 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-11 12:07:02,655 DEBUG   HandlerThread:105878 [system_info.py:probe():240] Probing system done
2023-07-11 12:07:02,656 DEBUG   HandlerThread:105878 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-11T04:07:02.651685', 'startedAt': '2023-07-11T04:07:01.494641', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3661.1659999999997, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 5099.974, 'min': 800.0, 'max': 5100.0}, {'current': 5100.103, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5099.923, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5099.934, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.019763946533203125}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-11 12:07:02,656 INFO    HandlerThread:105878 [system_monitor.py:probe():211] Finished collecting system info
2023-07-11 12:07:02,656 INFO    HandlerThread:105878 [system_monitor.py:probe():214] Publishing system info
2023-07-11 12:07:02,656 DEBUG   HandlerThread:105878 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-11 12:07:02,656 DEBUG   HandlerThread:105878 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-11 12:07:02,656 DEBUG   HandlerThread:105878 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-11 12:07:03,425 INFO    Thread-17 :105878 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120701-e7ceae04/files/requirements.txt
2023-07-11 12:07:03,426 INFO    Thread-17 :105878 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120701-e7ceae04/files/wandb-summary.json
2023-07-11 12:07:03,426 INFO    Thread-17 :105878 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120701-e7ceae04/files/conda-environment.yaml
2023-07-11 12:07:03,548 DEBUG   HandlerThread:105878 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-11 12:07:03,549 INFO    HandlerThread:105878 [system_monitor.py:probe():216] Finished publishing system info
2023-07-11 12:07:03,552 DEBUG   SenderThread:105878 [sender.py:send():369] send: files
2023-07-11 12:07:03,552 INFO    SenderThread:105878 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-11 12:07:03,558 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:07:03,560 DEBUG   SenderThread:105878 [sender.py:send_request():396] send_request: stop_status
2023-07-11 12:07:04,043 ERROR   wandb-upload_0:105878 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/e7ceae04/wandb-metadata.json?Expires=1689134823&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Uh0pQvtbbgu%2BF854chHV2AVbgPJgy%2F829Wm2vkDpZyye8AAn5Id6%2FH0PZMiWNY5myVzmjS4vh5FbTAV7tWg9ANpeZ6v1C7qYe%2BQqZ0%2B7puj2nMMSdAExE2hh1wMzNzqSDiIqt24PMtSAQX2nDjjecv6jGfK1zGkawFalEPUtEGyDAkyZQQjDolWHqZfGwNP%2F0KML8bO0BklxvDCqUWsfSxDlu%2FSICTTbk28jpLkvzPjjOVHlTqOESRzNqSF%2B%2Fuw5H74O5c3NVjdpvWPl7NDsID1ENrjUGSPhzBCCkZcKJLhhkhKRHHzMczNgIEVN%2FWw50%2BSY%2BQ2mNYza7FYMdY3o9A%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/e7ceae04/wandb-metadata.json?Expires=1689134823&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Uh0pQvtbbgu%2BF854chHV2AVbgPJgy%2F829Wm2vkDpZyye8AAn5Id6%2FH0PZMiWNY5myVzmjS4vh5FbTAV7tWg9ANpeZ6v1C7qYe%2BQqZ0%2B7puj2nMMSdAExE2hh1wMzNzqSDiIqt24PMtSAQX2nDjjecv6jGfK1zGkawFalEPUtEGyDAkyZQQjDolWHqZfGwNP%2F0KML8bO0BklxvDCqUWsfSxDlu%2FSICTTbk28jpLkvzPjjOVHlTqOESRzNqSF%2B%2Fuw5H74O5c3NVjdpvWPl7NDsID1ENrjUGSPhzBCCkZcKJLhhkhKRHHzMczNgIEVN%2FWw50%2BSY%2BQ2mNYza7FYMdY3o9A%3D%3D
2023-07-11 12:07:04,043 ERROR   wandb-upload_0:105878 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3614'}
2023-07-11 12:07:04,043 ERROR   wandb-upload_0:105878 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/e7ceae04/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-11 12:07:04,157 DEBUG   SenderThread:105878 [sender.py:send():369] send: telemetry
2023-07-11 12:07:04,424 INFO    Thread-17 :105878 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120701-e7ceae04/files/conda-environment.yaml
2023-07-11 12:07:04,426 INFO    Thread-17 :105878 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120701-e7ceae04/files/output.log
2023-07-11 12:07:04,427 INFO    Thread-17 :105878 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120701-e7ceae04/files/wandb-metadata.json
2023-07-11 12:07:04,764 ERROR   wandb-upload_0:105878 [upload_job.py:push():136] Failed to upload file: /tmp/tmp5fuv46_cwandb/i8gn5vuz-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/e7ceae04/wandb-metadata.json?Expires=1689134823&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Uh0pQvtbbgu%2BF854chHV2AVbgPJgy%2F829Wm2vkDpZyye8AAn5Id6%2FH0PZMiWNY5myVzmjS4vh5FbTAV7tWg9ANpeZ6v1C7qYe%2BQqZ0%2B7puj2nMMSdAExE2hh1wMzNzqSDiIqt24PMtSAQX2nDjjecv6jGfK1zGkawFalEPUtEGyDAkyZQQjDolWHqZfGwNP%2F0KML8bO0BklxvDCqUWsfSxDlu%2FSICTTbk28jpLkvzPjjOVHlTqOESRzNqSF%2B%2Fuw5H74O5c3NVjdpvWPl7NDsID1ENrjUGSPhzBCCkZcKJLhhkhKRHHzMczNgIEVN%2FWw50%2BSY%2BQ2mNYza7FYMdY3o9A%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 12:07:04,982 ERROR   Thread-16 :105878 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmp5fuv46_cwandb/i8gn5vuz-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/e7ceae04/wandb-metadata.json?Expires=1689134823&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Uh0pQvtbbgu%2BF854chHV2AVbgPJgy%2F829Wm2vkDpZyye8AAn5Id6%2FH0PZMiWNY5myVzmjS4vh5FbTAV7tWg9ANpeZ6v1C7qYe%2BQqZ0%2B7puj2nMMSdAExE2hh1wMzNzqSDiIqt24PMtSAQX2nDjjecv6jGfK1zGkawFalEPUtEGyDAkyZQQjDolWHqZfGwNP%2F0KML8bO0BklxvDCqUWsfSxDlu%2FSICTTbk28jpLkvzPjjOVHlTqOESRzNqSF%2B%2Fuw5H74O5c3NVjdpvWPl7NDsID1ENrjUGSPhzBCCkZcKJLhhkhKRHHzMczNgIEVN%2FWw50%2BSY%2BQ2mNYza7FYMdY3o9A%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 12:07:06,424 INFO    Thread-17 :105878 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120701-e7ceae04/files/output.log
2023-07-11 12:07:07,187 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:07:08,425 INFO    Thread-17 :105878 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120701-e7ceae04/files/output.log
2023-07-11 12:07:12,467 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:07:15,255 DEBUG   SenderThread:105878 [sender.py:send():369] send: telemetry
2023-07-11 12:07:16,427 INFO    Thread-17 :105878 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120701-e7ceae04/files/output.log
2023-07-11 12:07:18,322 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:07:18,557 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:07:18,557 DEBUG   SenderThread:105878 [sender.py:send_request():396] send_request: stop_status
2023-07-11 12:07:22,430 INFO    Thread-17 :105878 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120701-e7ceae04/files/output.log
2023-07-11 12:07:23,690 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:07:24,430 INFO    Thread-17 :105878 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120701-e7ceae04/files/output.log
2023-07-11 12:07:28,690 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:07:33,558 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:07:33,558 DEBUG   SenderThread:105878 [sender.py:send_request():396] send_request: stop_status
2023-07-11 12:07:33,787 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:07:34,433 INFO    Thread-17 :105878 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120701-e7ceae04/files/config.yaml
2023-07-11 12:07:39,059 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:07:44,060 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:07:48,557 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:07:48,558 DEBUG   SenderThread:105878 [sender.py:send_request():396] send_request: stop_status
2023-07-11 12:07:49,791 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:07:54,792 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:07:59,792 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:08:02,636 DEBUG   SystemMonitor:105878 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-11 12:08:02,638 DEBUG   SenderThread:105878 [sender.py:send():369] send: stats
2023-07-11 12:08:03,558 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:08:03,558 DEBUG   SenderThread:105878 [sender.py:send_request():396] send_request: stop_status
2023-07-11 12:08:05,786 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:08:10,787 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:08:15,787 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:08:18,558 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:08:18,558 DEBUG   SenderThread:105878 [sender.py:send_request():396] send_request: stop_status
2023-07-11 12:08:20,792 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:08:25,793 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:08:30,793 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:08:32,639 DEBUG   SenderThread:105878 [sender.py:send():369] send: stats
2023-07-11 12:08:33,558 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:08:33,558 DEBUG   SenderThread:105878 [sender.py:send_request():396] send_request: stop_status
2023-07-11 12:08:35,798 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:08:40,799 DEBUG   HandlerThread:105878 [handler.py:handle_request():144] handle_request: status_report
