2023-07-11 12:03:19,186 INFO    StreamThr :105088 [internal.py:wandb_internal():86] W&B internal server running at pid: 105088, started at: 2023-07-11 12:03:19.185737
2023-07-11 12:03:19,190 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status
2023-07-11 12:03:19,192 INFO    WriterThread:105088 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120319-vru1ejdv/run-vru1ejdv.wandb
2023-07-11 12:03:19,193 DEBUG   SenderThread:105088 [sender.py:send():369] send: header
2023-07-11 12:03:19,193 DEBUG   SenderThread:105088 [sender.py:send():369] send: run
2023-07-11 12:03:20,127 INFO    SenderThread:105088 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120319-vru1ejdv/files
2023-07-11 12:03:20,127 INFO    SenderThread:105088 [sender.py:_start_run_threads():1100] run started: vru1ejdv with start time 1689048199.186526
2023-07-11 12:03:20,127 DEBUG   SenderThread:105088 [sender.py:send_request():396] send_request: summary_record
2023-07-11 12:03:20,128 INFO    SenderThread:105088 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-11 12:03:20,129 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: check_version
2023-07-11 12:03:20,129 DEBUG   SenderThread:105088 [sender.py:send_request():396] send_request: check_version
2023-07-11 12:03:20,321 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: run_start
2023-07-11 12:03:20,326 DEBUG   HandlerThread:105088 [system_info.py:__init__():31] System info init
2023-07-11 12:03:20,326 DEBUG   HandlerThread:105088 [system_info.py:__init__():46] System info init done
2023-07-11 12:03:20,326 INFO    HandlerThread:105088 [system_monitor.py:start():181] Starting system monitor
2023-07-11 12:03:20,327 INFO    HandlerThread:105088 [system_monitor.py:probe():201] Collecting system info
2023-07-11 12:03:20,328 INFO    SystemMonitor:105088 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-11 12:03:20,330 INFO    SystemMonitor:105088 [interfaces.py:start():190] Started cpu monitoring
2023-07-11 12:03:20,331 INFO    SystemMonitor:105088 [interfaces.py:start():190] Started disk monitoring
2023-07-11 12:03:20,332 INFO    SystemMonitor:105088 [interfaces.py:start():190] Started gpu monitoring
2023-07-11 12:03:20,333 INFO    SystemMonitor:105088 [interfaces.py:start():190] Started memory monitoring
2023-07-11 12:03:20,335 INFO    SystemMonitor:105088 [interfaces.py:start():190] Started network monitoring
2023-07-11 12:03:20,345 DEBUG   HandlerThread:105088 [system_info.py:probe():195] Probing system
2023-07-11 12:03:20,349 DEBUG   HandlerThread:105088 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-11 12:03:20,349 DEBUG   HandlerThread:105088 [system_info.py:probe():240] Probing system done
2023-07-11 12:03:20,349 DEBUG   HandlerThread:105088 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-11T04:03:20.345259', 'startedAt': '2023-07-11T04:03:19.173847', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3969.3590416666666, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 4700.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 4700.0, 'min': 800.0, 'max': 5100.0}, {'current': 4603.727, 'min': 800.0, 'max': 5100.0}, {'current': 4386.555, 'min': 800.0, 'max': 5100.0}, {'current': 4699.846, 'min': 800.0, 'max': 5100.0}, {'current': 4600.0, 'min': 800.0, 'max': 5100.0}, {'current': 4599.913, 'min': 800.0, 'max': 5100.0}, {'current': 4699.685, 'min': 800.0, 'max': 5200.0}, {'current': 4710.432, 'min': 800.0, 'max': 5200.0}, {'current': 4590.956, 'min': 800.0, 'max': 5200.0}, {'current': 4540.41, 'min': 800.0, 'max': 5200.0}, {'current': 4700.375, 'min': 800.0, 'max': 5100.0}, {'current': 4699.519, 'min': 800.0, 'max': 5100.0}, {'current': 4533.238, 'min': 800.0, 'max': 5100.0}, {'current': 4694.946, 'min': 800.0, 'max': 5100.0}, {'current': 3700.46, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 3714.942, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.019687652587890625}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-11 12:03:20,349 INFO    HandlerThread:105088 [system_monitor.py:probe():211] Finished collecting system info
2023-07-11 12:03:20,349 INFO    HandlerThread:105088 [system_monitor.py:probe():214] Publishing system info
2023-07-11 12:03:20,349 DEBUG   HandlerThread:105088 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-11 12:03:20,350 DEBUG   HandlerThread:105088 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-11 12:03:20,350 DEBUG   HandlerThread:105088 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-11 12:03:21,131 INFO    Thread-17 :105088 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120319-vru1ejdv/files/wandb-summary.json
2023-07-11 12:03:21,132 INFO    Thread-17 :105088 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120319-vru1ejdv/files/requirements.txt
2023-07-11 12:03:21,132 INFO    Thread-17 :105088 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120319-vru1ejdv/files/conda-environment.yaml
2023-07-11 12:03:21,231 DEBUG   HandlerThread:105088 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-11 12:03:21,233 INFO    HandlerThread:105088 [system_monitor.py:probe():216] Finished publishing system info
2023-07-11 12:03:21,238 DEBUG   SenderThread:105088 [sender.py:send():369] send: files
2023-07-11 12:03:21,238 INFO    SenderThread:105088 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-11 12:03:21,247 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:03:21,250 DEBUG   SenderThread:105088 [sender.py:send_request():396] send_request: stop_status
2023-07-11 12:03:21,704 ERROR   wandb-upload_0:105088 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/vru1ejdv/wandb-metadata.json?Expires=1689134601&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XfsHPrIEF4ZbWyfpXc%2B3FrX9mlmA6QH3Ri6PDUgEesomH1%2Blk3PVIdrAgF975d2lzOGpXez54KTEcY44TDyUNKsN4eQdiyueJrxt5AldQmJwvalMEjb2%2BjfzfbFbj2H%2BCz%2B9IlLNywXHlphU1Dku88NNDVzcFUNVll3SDox0SL6spC0EiW2fKtutm3qjo2tIgMvHL64NapIXieVODfH6VCPflcGqrZgigKCVf5iy%2FkhE6r5aIZLSIwJ30Io1BYv3R9KJRMLl2P29INvh0gJB6ZQmQgfXimsfUMrehEbXrGVWK0Rq%2B2F2Y4CczY%2B1Z20fDhtsrLDXX0mfXVOUHuOK9Q%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/vru1ejdv/wandb-metadata.json?Expires=1689134601&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XfsHPrIEF4ZbWyfpXc%2B3FrX9mlmA6QH3Ri6PDUgEesomH1%2Blk3PVIdrAgF975d2lzOGpXez54KTEcY44TDyUNKsN4eQdiyueJrxt5AldQmJwvalMEjb2%2BjfzfbFbj2H%2BCz%2B9IlLNywXHlphU1Dku88NNDVzcFUNVll3SDox0SL6spC0EiW2fKtutm3qjo2tIgMvHL64NapIXieVODfH6VCPflcGqrZgigKCVf5iy%2FkhE6r5aIZLSIwJ30Io1BYv3R9KJRMLl2P29INvh0gJB6ZQmQgfXimsfUMrehEbXrGVWK0Rq%2B2F2Y4CczY%2B1Z20fDhtsrLDXX0mfXVOUHuOK9Q%3D%3D
2023-07-11 12:03:21,704 ERROR   wandb-upload_0:105088 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3632'}
2023-07-11 12:03:21,704 ERROR   wandb-upload_0:105088 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/vru1ejdv/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-11 12:03:21,817 DEBUG   SenderThread:105088 [sender.py:send():369] send: telemetry
2023-07-11 12:03:22,131 INFO    Thread-17 :105088 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120319-vru1ejdv/files/conda-environment.yaml
2023-07-11 12:03:22,131 INFO    Thread-17 :105088 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120319-vru1ejdv/files/output.log
2023-07-11 12:03:22,131 INFO    Thread-17 :105088 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120319-vru1ejdv/files/wandb-metadata.json
2023-07-11 12:03:22,272 ERROR   wandb-upload_0:105088 [upload_job.py:push():136] Failed to upload file: /tmp/tmp5826qk2awandb/bivxae8t-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/vru1ejdv/wandb-metadata.json?Expires=1689134601&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XfsHPrIEF4ZbWyfpXc%2B3FrX9mlmA6QH3Ri6PDUgEesomH1%2Blk3PVIdrAgF975d2lzOGpXez54KTEcY44TDyUNKsN4eQdiyueJrxt5AldQmJwvalMEjb2%2BjfzfbFbj2H%2BCz%2B9IlLNywXHlphU1Dku88NNDVzcFUNVll3SDox0SL6spC0EiW2fKtutm3qjo2tIgMvHL64NapIXieVODfH6VCPflcGqrZgigKCVf5iy%2FkhE6r5aIZLSIwJ30Io1BYv3R9KJRMLl2P29INvh0gJB6ZQmQgfXimsfUMrehEbXrGVWK0Rq%2B2F2Y4CczY%2B1Z20fDhtsrLDXX0mfXVOUHuOK9Q%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 12:03:22,494 ERROR   Thread-16 :105088 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmp5826qk2awandb/bivxae8t-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/vru1ejdv/wandb-metadata.json?Expires=1689134601&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=XfsHPrIEF4ZbWyfpXc%2B3FrX9mlmA6QH3Ri6PDUgEesomH1%2Blk3PVIdrAgF975d2lzOGpXez54KTEcY44TDyUNKsN4eQdiyueJrxt5AldQmJwvalMEjb2%2BjfzfbFbj2H%2BCz%2B9IlLNywXHlphU1Dku88NNDVzcFUNVll3SDox0SL6spC0EiW2fKtutm3qjo2tIgMvHL64NapIXieVODfH6VCPflcGqrZgigKCVf5iy%2FkhE6r5aIZLSIwJ30Io1BYv3R9KJRMLl2P29INvh0gJB6ZQmQgfXimsfUMrehEbXrGVWK0Rq%2B2F2Y4CczY%2B1Z20fDhtsrLDXX0mfXVOUHuOK9Q%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 12:03:24,131 INFO    Thread-17 :105088 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120319-vru1ejdv/files/output.log
2023-07-11 12:03:24,595 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:03:26,132 INFO    Thread-17 :105088 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120319-vru1ejdv/files/output.log
2023-07-11 12:03:29,811 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:03:32,134 INFO    Thread-17 :105088 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120319-vru1ejdv/files/output.log
2023-07-11 12:03:32,414 DEBUG   SenderThread:105088 [sender.py:send():369] send: telemetry
2023-07-11 12:03:34,135 INFO    Thread-17 :105088 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120319-vru1ejdv/files/output.log
2023-07-11 12:03:35,495 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:03:36,244 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:03:36,245 DEBUG   SenderThread:105088 [sender.py:send_request():396] send_request: stop_status
2023-07-11 12:03:40,140 INFO    Thread-17 :105088 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120319-vru1ejdv/files/output.log
2023-07-11 12:03:41,005 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:03:42,140 INFO    Thread-17 :105088 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120319-vru1ejdv/files/output.log
2023-07-11 12:03:46,005 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:03:51,011 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:03:51,245 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:03:51,284 DEBUG   SenderThread:105088 [sender.py:send_request():396] send_request: stop_status
2023-07-11 12:03:52,143 INFO    Thread-17 :105088 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_120319-vru1ejdv/files/config.yaml
2023-07-11 12:03:56,506 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:04:01,507 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:04:06,245 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:04:06,245 DEBUG   SenderThread:105088 [sender.py:send_request():396] send_request: stop_status
2023-07-11 12:04:08,289 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:04:13,289 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:04:18,290 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:04:20,335 DEBUG   SystemMonitor:105088 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-11 12:04:20,337 DEBUG   SenderThread:105088 [sender.py:send():369] send: stats
2023-07-11 12:04:21,245 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:04:21,245 DEBUG   SenderThread:105088 [sender.py:send_request():396] send_request: stop_status
2023-07-11 12:04:23,466 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:04:28,467 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:04:33,467 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:04:36,245 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:04:36,245 DEBUG   SenderThread:105088 [sender.py:send_request():396] send_request: stop_status
2023-07-11 12:04:38,468 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:04:43,469 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:04:48,469 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:04:50,338 DEBUG   SenderThread:105088 [sender.py:send():369] send: stats
2023-07-11 12:04:51,245 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:04:51,246 DEBUG   SenderThread:105088 [sender.py:send_request():396] send_request: stop_status
2023-07-11 12:04:53,476 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:04:58,477 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:05:03,478 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:05:06,245 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:05:06,246 DEBUG   SenderThread:105088 [sender.py:send_request():396] send_request: stop_status
2023-07-11 12:05:08,505 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:05:13,506 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:05:18,507 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 12:05:20,341 DEBUG   SenderThread:105088 [sender.py:send():369] send: stats
2023-07-11 12:05:21,245 DEBUG   HandlerThread:105088 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 12:05:21,246 DEBUG   SenderThread:105088 [sender.py:send_request():396] send_request: stop_status
