2023-07-10 15:57:45,286 INFO    StreamThr :51714 [internal.py:wandb_internal():86] W&B internal server running at pid: 51714, started at: 2023-07-10 15:57:45.286165
2023-07-10 15:57:45,292 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status
2023-07-10 15:57:45,295 INFO    WriterThread:51714 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_155745-zs03bfo2/run-zs03bfo2.wandb
2023-07-10 15:57:45,295 DEBUG   SenderThread:51714 [sender.py:send():369] send: header
2023-07-10 15:57:45,295 DEBUG   SenderThread:51714 [sender.py:send():369] send: run
2023-07-10 15:57:46,154 INFO    SenderThread:51714 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_155745-zs03bfo2/files
2023-07-10 15:57:46,154 INFO    SenderThread:51714 [sender.py:_start_run_threads():1100] run started: zs03bfo2 with start time 1688975865.285791
2023-07-10 15:57:46,155 DEBUG   SenderThread:51714 [sender.py:send_request():396] send_request: summary_record
2023-07-10 15:57:46,155 INFO    SenderThread:51714 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 15:57:46,160 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 15:57:46,160 DEBUG   SenderThread:51714 [sender.py:send_request():396] send_request: check_version
2023-07-10 15:57:46,342 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 15:57:46,348 DEBUG   HandlerThread:51714 [system_info.py:__init__():31] System info init
2023-07-10 15:57:46,349 DEBUG   HandlerThread:51714 [system_info.py:__init__():46] System info init done
2023-07-10 15:57:46,349 INFO    HandlerThread:51714 [system_monitor.py:start():181] Starting system monitor
2023-07-10 15:57:46,349 INFO    SystemMonitor:51714 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 15:57:46,349 INFO    HandlerThread:51714 [system_monitor.py:probe():201] Collecting system info
2023-07-10 15:57:46,351 INFO    SystemMonitor:51714 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 15:57:46,354 INFO    SystemMonitor:51714 [interfaces.py:start():190] Started disk monitoring
2023-07-10 15:57:46,355 INFO    SystemMonitor:51714 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 15:57:46,358 INFO    SystemMonitor:51714 [interfaces.py:start():190] Started memory monitoring
2023-07-10 15:57:46,360 INFO    SystemMonitor:51714 [interfaces.py:start():190] Started network monitoring
2023-07-10 15:57:46,377 DEBUG   HandlerThread:51714 [system_info.py:probe():195] Probing system
2023-07-10 15:57:46,382 DEBUG   HandlerThread:51714 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 15:57:46,383 DEBUG   HandlerThread:51714 [system_info.py:probe():240] Probing system done
2023-07-10 15:57:46,383 DEBUG   HandlerThread:51714 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T07:57:46.377178', 'startedAt': '2023-07-10T07:57:45.275678', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3917.9850416666663, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5000.183, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5095.114, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.027, 'min': 800.0, 'max': 5200.0}, {'current': 5035.453, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5099.931, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 3699.09, 'min': 800.0, 'max': 4100.0}, {'current': 3699.93, 'min': 800.0, 'max': 4100.0}, {'current': 3701.913, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.018444061279296875}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185562133789062}}
2023-07-10 15:57:46,383 INFO    HandlerThread:51714 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 15:57:46,383 INFO    HandlerThread:51714 [system_monitor.py:probe():214] Publishing system info
2023-07-10 15:57:46,383 DEBUG   HandlerThread:51714 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 15:57:46,383 DEBUG   HandlerThread:51714 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 15:57:46,383 DEBUG   HandlerThread:51714 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 15:57:47,157 INFO    Thread-17 :51714 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_155745-zs03bfo2/files/wandb-summary.json
2023-07-10 15:57:47,157 INFO    Thread-17 :51714 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_155745-zs03bfo2/files/requirements.txt
2023-07-10 15:57:47,157 INFO    Thread-17 :51714 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_155745-zs03bfo2/files/conda-environment.yaml
2023-07-10 15:57:47,376 DEBUG   HandlerThread:51714 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 15:57:47,378 INFO    HandlerThread:51714 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 15:57:47,381 DEBUG   SenderThread:51714 [sender.py:send():369] send: files
2023-07-10 15:57:47,382 INFO    SenderThread:51714 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 15:57:47,388 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 15:57:47,389 DEBUG   SenderThread:51714 [sender.py:send_request():396] send_request: stop_status
2023-07-10 15:57:47,828 ERROR   wandb-upload_0:51714 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/zs03bfo2/wandb-metadata.json?Expires=1689062267&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YcD54z4vwvlVE6cSWAi%2FpuTcbL2yPBNT1KR0%2Fsy1SxoLRoLZ5eGhdLhGOom4AuiHFxA0HlsrRKAlOMRISPYZMZfoT%2Ftj01Z4nyG%2BmqKqTRNxQvWTpArSLENF91RzS4oueKt6z1T0Z%2Fa78aT4jEWBn8hMYhSRnXswwLjb3HfKC01k1C7G2ITwiwTsdt%2Bs8TM3qKMsX6VIBC6mCUeRqwJ0yBSJcNJ8Z5TgpsFEpjtxVFUBEvHIRXFaMdqGNvux1UrMhjDslE3yKXKQHPtt8WlZNrXVX3D6iAKI8UEPN1avXhQ%2BkVCvULcYVVGIHx%2F2ccUkUAwmPS8BZlY0Vl%2Fq2yKVfQ%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/zs03bfo2/wandb-metadata.json?Expires=1689062267&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YcD54z4vwvlVE6cSWAi%2FpuTcbL2yPBNT1KR0%2Fsy1SxoLRoLZ5eGhdLhGOom4AuiHFxA0HlsrRKAlOMRISPYZMZfoT%2Ftj01Z4nyG%2BmqKqTRNxQvWTpArSLENF91RzS4oueKt6z1T0Z%2Fa78aT4jEWBn8hMYhSRnXswwLjb3HfKC01k1C7G2ITwiwTsdt%2Bs8TM3qKMsX6VIBC6mCUeRqwJ0yBSJcNJ8Z5TgpsFEpjtxVFUBEvHIRXFaMdqGNvux1UrMhjDslE3yKXKQHPtt8WlZNrXVX3D6iAKI8UEPN1avXhQ%2BkVCvULcYVVGIHx%2F2ccUkUAwmPS8BZlY0Vl%2Fq2yKVfQ%3D%3D
2023-07-10 15:57:47,828 ERROR   wandb-upload_0:51714 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3620'}
2023-07-10 15:57:47,828 ERROR   wandb-upload_0:51714 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/zs03bfo2/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 15:57:47,990 DEBUG   SenderThread:51714 [sender.py:send():369] send: telemetry
2023-07-10 15:57:48,157 INFO    Thread-17 :51714 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_155745-zs03bfo2/files/conda-environment.yaml
2023-07-10 15:57:48,157 INFO    Thread-17 :51714 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_155745-zs03bfo2/files/wandb-metadata.json
2023-07-10 15:57:48,157 INFO    Thread-17 :51714 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_155745-zs03bfo2/files/output.log
2023-07-10 15:57:48,404 ERROR   wandb-upload_0:51714 [upload_job.py:push():136] Failed to upload file: /tmp/tmpqs5vura9wandb/bxeclk9a-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/zs03bfo2/wandb-metadata.json?Expires=1689062267&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YcD54z4vwvlVE6cSWAi%2FpuTcbL2yPBNT1KR0%2Fsy1SxoLRoLZ5eGhdLhGOom4AuiHFxA0HlsrRKAlOMRISPYZMZfoT%2Ftj01Z4nyG%2BmqKqTRNxQvWTpArSLENF91RzS4oueKt6z1T0Z%2Fa78aT4jEWBn8hMYhSRnXswwLjb3HfKC01k1C7G2ITwiwTsdt%2Bs8TM3qKMsX6VIBC6mCUeRqwJ0yBSJcNJ8Z5TgpsFEpjtxVFUBEvHIRXFaMdqGNvux1UrMhjDslE3yKXKQHPtt8WlZNrXVX3D6iAKI8UEPN1avXhQ%2BkVCvULcYVVGIHx%2F2ccUkUAwmPS8BZlY0Vl%2Fq2yKVfQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 15:57:48,631 ERROR   Thread-16 :51714 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpqs5vura9wandb/bxeclk9a-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/zs03bfo2/wandb-metadata.json?Expires=1689062267&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YcD54z4vwvlVE6cSWAi%2FpuTcbL2yPBNT1KR0%2Fsy1SxoLRoLZ5eGhdLhGOom4AuiHFxA0HlsrRKAlOMRISPYZMZfoT%2Ftj01Z4nyG%2BmqKqTRNxQvWTpArSLENF91RzS4oueKt6z1T0Z%2Fa78aT4jEWBn8hMYhSRnXswwLjb3HfKC01k1C7G2ITwiwTsdt%2Bs8TM3qKMsX6VIBC6mCUeRqwJ0yBSJcNJ8Z5TgpsFEpjtxVFUBEvHIRXFaMdqGNvux1UrMhjDslE3yKXKQHPtt8WlZNrXVX3D6iAKI8UEPN1avXhQ%2BkVCvULcYVVGIHx%2F2ccUkUAwmPS8BZlY0Vl%2Fq2yKVfQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 15:57:50,156 INFO    Thread-17 :51714 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_155745-zs03bfo2/files/output.log
2023-07-10 15:57:50,884 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:57:52,156 INFO    Thread-17 :51714 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_155745-zs03bfo2/files/output.log
2023-07-10 15:57:56,105 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:57:58,210 DEBUG   SenderThread:51714 [sender.py:send():369] send: telemetry
2023-07-10 15:58:00,159 INFO    Thread-17 :51714 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_155745-zs03bfo2/files/output.log
2023-07-10 15:58:01,281 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:58:02,387 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 15:58:02,388 DEBUG   SenderThread:51714 [sender.py:send_request():396] send_request: stop_status
2023-07-10 15:58:04,161 INFO    Thread-17 :51714 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_155745-zs03bfo2/files/output.log
2023-07-10 15:58:07,092 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:58:12,093 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:58:17,099 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:58:17,387 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 15:58:17,437 DEBUG   SenderThread:51714 [sender.py:send_request():396] send_request: stop_status
2023-07-10 15:58:18,166 INFO    Thread-17 :51714 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_155745-zs03bfo2/files/config.yaml
2023-07-10 15:58:22,671 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:58:27,672 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:58:32,388 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 15:58:32,388 DEBUG   SenderThread:51714 [sender.py:send_request():396] send_request: stop_status
2023-07-10 15:58:33,622 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:58:38,623 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:58:43,624 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:58:46,360 DEBUG   SystemMonitor:51714 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-10 15:58:46,362 DEBUG   SenderThread:51714 [sender.py:send():369] send: stats
2023-07-10 15:58:47,388 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 15:58:47,388 DEBUG   SenderThread:51714 [sender.py:send_request():396] send_request: stop_status
2023-07-10 15:58:49,623 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:58:54,624 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:58:59,625 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:59:02,388 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 15:59:02,388 DEBUG   SenderThread:51714 [sender.py:send_request():396] send_request: stop_status
2023-07-10 15:59:04,629 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:59:09,630 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:59:14,630 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:59:16,363 DEBUG   SenderThread:51714 [sender.py:send():369] send: stats
2023-07-10 15:59:17,388 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 15:59:17,388 DEBUG   SenderThread:51714 [sender.py:send_request():396] send_request: stop_status
2023-07-10 15:59:20,616 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:59:25,617 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:59:30,619 DEBUG   HandlerThread:51714 [handler.py:handle_request():144] handle_request: status_report
